package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SwAccessimop generated by hbm2java
 */
public class SwAccessimop implements java.io.Serializable {

	private long sequSwAccessimop;
	private String textKsogSoggCfiscale;
	private String textKsogSoggDenominazione;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private Date dttmFaatDataAccesso;

	public SwAccessimop() {
	}

	public SwAccessimop(long sequSwAccessimop) {
		this.sequSwAccessimop = sequSwAccessimop;
	}

	public SwAccessimop(long sequSwAccessimop, String textKsogSoggCfiscale,
			String textKsogSoggDenominazione, String textKsogFogiCodFormaGiur,
			String descKsogFogiDescFormaGiu, Date dttmFaatDataAccesso) {
		this.sequSwAccessimop = sequSwAccessimop;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.dttmFaatDataAccesso = dttmFaatDataAccesso;
	}

	public long getSequSwAccessimop() {
		return this.sequSwAccessimop;
	}

	public void setSequSwAccessimop(long sequSwAccessimop) {
		this.sequSwAccessimop = sequSwAccessimop;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogSoggDenominazione() {
		return this.textKsogSoggDenominazione;
	}

	public void setTextKsogSoggDenominazione(String textKsogSoggDenominazione) {
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public Date getDttmFaatDataAccesso() {
		return this.dttmFaatDataAccesso;
	}

	public void setDttmFaatDataAccesso(Date dttmFaatDataAccesso) {
		this.dttmFaatDataAccesso = dttmFaatDataAccesso;
	}

}
