package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

/**
 * SwAnagraficasoggetticorrelati generated by hbm2java
 */
public class SwAnagraficasoggetticorrelati implements java.io.Serializable {

	private long sequSwAnagraficasoggcorr;
	private String textKsogSoggCfiscale;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String codiKregKregId;
	private String descKregKregDescRegione;
	private String textCodFonte;
	private String descDimensione;
	private String textCcupTipiCodTipInv;
	private String codiKurpUrpiCodLocProg;
	private Boolean numeKscpRusoCodRuoSogg;
	private String descKscpRusoDescRuoSogg;
	private String textKscpSoggCfiscSoggCorr;
	private String textKscpSoggDenomSoggCorr;
	private String textKscpKfogCodFormaGiur;
	private String textKscpKfogDescFormaGiu;
	private String textKscpSae1CodAtecoLiv1;
	private String textKscpSae1DescSettLiv1;
	private String codiKprvKprvCodProvincia;
	private String textKprvKprvDescProvincia;
	private String codiKcomKcomId;
	private String textKcomKcomDescComune;
	private String textKscpScpiDenomRappLeg;
	private Boolean numeKscpDiimCodDimImpr;
	private String descKscpDiimDescDimImpr;
	private String textKscpCladCodClasAdd;
	private String descKscpCladDescClasAdd;
	private String textKscpScpiIndirizzo;
	private String numeKscpScpiCap;

	public SwAnagraficasoggetticorrelati() {
	}

	public SwAnagraficasoggetticorrelati(long sequSwAnagraficasoggcorr) {
		this.sequSwAnagraficasoggcorr = sequSwAnagraficasoggcorr;
	}

	public SwAnagraficasoggetticorrelati(long sequSwAnagraficasoggcorr,
			String textKsogSoggCfiscale, String textKsogFogiCodFormaGiur,
			String descKsogFogiDescFormaGiu, String codiCcupCcupAnagCcup,
			String textCcupSipiCodSetInv, String descCcupSipiDescSetCup,
			String textCcupSspiCodSsetInv, String descCcupSspiDescSsetCup,
			String textCcupCipiCodCatInv, String descCcupCipiDescCatCup,
			String codiKregKregId, String descKregKregDescRegione,
			String textCodFonte, String descDimensione,
			String textCcupTipiCodTipInv, String codiKurpUrpiCodLocProg,
			Boolean numeKscpRusoCodRuoSogg, String descKscpRusoDescRuoSogg,
			String textKscpSoggCfiscSoggCorr, String textKscpSoggDenomSoggCorr,
			String textKscpKfogCodFormaGiur, String textKscpKfogDescFormaGiu,
			String textKscpSae1CodAtecoLiv1, String textKscpSae1DescSettLiv1,
			String codiKprvKprvCodProvincia, String textKprvKprvDescProvincia,
			String codiKcomKcomId, String textKcomKcomDescComune,
			String textKscpScpiDenomRappLeg, Boolean numeKscpDiimCodDimImpr,
			String descKscpDiimDescDimImpr, String textKscpCladCodClasAdd,
			String descKscpCladDescClasAdd, String textKscpScpiIndirizzo,
			String numeKscpScpiCap) {
		this.sequSwAnagraficasoggcorr = sequSwAnagraficasoggcorr;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.codiKregKregId = codiKregKregId;
		this.descKregKregDescRegione = descKregKregDescRegione;
		this.textCodFonte = textCodFonte;
		this.descDimensione = descDimensione;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
		this.numeKscpRusoCodRuoSogg = numeKscpRusoCodRuoSogg;
		this.descKscpRusoDescRuoSogg = descKscpRusoDescRuoSogg;
		this.textKscpSoggCfiscSoggCorr = textKscpSoggCfiscSoggCorr;
		this.textKscpSoggDenomSoggCorr = textKscpSoggDenomSoggCorr;
		this.textKscpKfogCodFormaGiur = textKscpKfogCodFormaGiur;
		this.textKscpKfogDescFormaGiu = textKscpKfogDescFormaGiu;
		this.textKscpSae1CodAtecoLiv1 = textKscpSae1CodAtecoLiv1;
		this.textKscpSae1DescSettLiv1 = textKscpSae1DescSettLiv1;
		this.codiKprvKprvCodProvincia = codiKprvKprvCodProvincia;
		this.textKprvKprvDescProvincia = textKprvKprvDescProvincia;
		this.codiKcomKcomId = codiKcomKcomId;
		this.textKcomKcomDescComune = textKcomKcomDescComune;
		this.textKscpScpiDenomRappLeg = textKscpScpiDenomRappLeg;
		this.numeKscpDiimCodDimImpr = numeKscpDiimCodDimImpr;
		this.descKscpDiimDescDimImpr = descKscpDiimDescDimImpr;
		this.textKscpCladCodClasAdd = textKscpCladCodClasAdd;
		this.descKscpCladDescClasAdd = descKscpCladDescClasAdd;
		this.textKscpScpiIndirizzo = textKscpScpiIndirizzo;
		this.numeKscpScpiCap = numeKscpScpiCap;
	}

	public long getSequSwAnagraficasoggcorr() {
		return this.sequSwAnagraficasoggcorr;
	}

	public void setSequSwAnagraficasoggcorr(long sequSwAnagraficasoggcorr) {
		this.sequSwAnagraficasoggcorr = sequSwAnagraficasoggcorr;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getCodiKregKregId() {
		return this.codiKregKregId;
	}

	public void setCodiKregKregId(String codiKregKregId) {
		this.codiKregKregId = codiKregKregId;
	}

	public String getDescKregKregDescRegione() {
		return this.descKregKregDescRegione;
	}

	public void setDescKregKregDescRegione(String descKregKregDescRegione) {
		this.descKregKregDescRegione = descKregKregDescRegione;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getDescDimensione() {
		return this.descDimensione;
	}

	public void setDescDimensione(String descDimensione) {
		this.descDimensione = descDimensione;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getCodiKurpUrpiCodLocProg() {
		return this.codiKurpUrpiCodLocProg;
	}

	public void setCodiKurpUrpiCodLocProg(String codiKurpUrpiCodLocProg) {
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
	}

	public Boolean getNumeKscpRusoCodRuoSogg() {
		return this.numeKscpRusoCodRuoSogg;
	}

	public void setNumeKscpRusoCodRuoSogg(Boolean numeKscpRusoCodRuoSogg) {
		this.numeKscpRusoCodRuoSogg = numeKscpRusoCodRuoSogg;
	}

	public String getDescKscpRusoDescRuoSogg() {
		return this.descKscpRusoDescRuoSogg;
	}

	public void setDescKscpRusoDescRuoSogg(String descKscpRusoDescRuoSogg) {
		this.descKscpRusoDescRuoSogg = descKscpRusoDescRuoSogg;
	}

	public String getTextKscpSoggCfiscSoggCorr() {
		return this.textKscpSoggCfiscSoggCorr;
	}

	public void setTextKscpSoggCfiscSoggCorr(String textKscpSoggCfiscSoggCorr) {
		this.textKscpSoggCfiscSoggCorr = textKscpSoggCfiscSoggCorr;
	}

	public String getTextKscpSoggDenomSoggCorr() {
		return this.textKscpSoggDenomSoggCorr;
	}

	public void setTextKscpSoggDenomSoggCorr(String textKscpSoggDenomSoggCorr) {
		this.textKscpSoggDenomSoggCorr = textKscpSoggDenomSoggCorr;
	}

	public String getTextKscpKfogCodFormaGiur() {
		return this.textKscpKfogCodFormaGiur;
	}

	public void setTextKscpKfogCodFormaGiur(String textKscpKfogCodFormaGiur) {
		this.textKscpKfogCodFormaGiur = textKscpKfogCodFormaGiur;
	}

	public String getTextKscpKfogDescFormaGiu() {
		return this.textKscpKfogDescFormaGiu;
	}

	public void setTextKscpKfogDescFormaGiu(String textKscpKfogDescFormaGiu) {
		this.textKscpKfogDescFormaGiu = textKscpKfogDescFormaGiu;
	}

	public String getTextKscpSae1CodAtecoLiv1() {
		return this.textKscpSae1CodAtecoLiv1;
	}

	public void setTextKscpSae1CodAtecoLiv1(String textKscpSae1CodAtecoLiv1) {
		this.textKscpSae1CodAtecoLiv1 = textKscpSae1CodAtecoLiv1;
	}

	public String getTextKscpSae1DescSettLiv1() {
		return this.textKscpSae1DescSettLiv1;
	}

	public void setTextKscpSae1DescSettLiv1(String textKscpSae1DescSettLiv1) {
		this.textKscpSae1DescSettLiv1 = textKscpSae1DescSettLiv1;
	}

	public String getCodiKprvKprvCodProvincia() {
		return this.codiKprvKprvCodProvincia;
	}

	public void setCodiKprvKprvCodProvincia(String codiKprvKprvCodProvincia) {
		this.codiKprvKprvCodProvincia = codiKprvKprvCodProvincia;
	}

	public String getTextKprvKprvDescProvincia() {
		return this.textKprvKprvDescProvincia;
	}

	public void setTextKprvKprvDescProvincia(String textKprvKprvDescProvincia) {
		this.textKprvKprvDescProvincia = textKprvKprvDescProvincia;
	}

	public String getCodiKcomKcomId() {
		return this.codiKcomKcomId;
	}

	public void setCodiKcomKcomId(String codiKcomKcomId) {
		this.codiKcomKcomId = codiKcomKcomId;
	}

	public String getTextKcomKcomDescComune() {
		return this.textKcomKcomDescComune;
	}

	public void setTextKcomKcomDescComune(String textKcomKcomDescComune) {
		this.textKcomKcomDescComune = textKcomKcomDescComune;
	}

	public String getTextKscpScpiDenomRappLeg() {
		return this.textKscpScpiDenomRappLeg;
	}

	public void setTextKscpScpiDenomRappLeg(String textKscpScpiDenomRappLeg) {
		this.textKscpScpiDenomRappLeg = textKscpScpiDenomRappLeg;
	}

	public Boolean getNumeKscpDiimCodDimImpr() {
		return this.numeKscpDiimCodDimImpr;
	}

	public void setNumeKscpDiimCodDimImpr(Boolean numeKscpDiimCodDimImpr) {
		this.numeKscpDiimCodDimImpr = numeKscpDiimCodDimImpr;
	}

	public String getDescKscpDiimDescDimImpr() {
		return this.descKscpDiimDescDimImpr;
	}

	public void setDescKscpDiimDescDimImpr(String descKscpDiimDescDimImpr) {
		this.descKscpDiimDescDimImpr = descKscpDiimDescDimImpr;
	}

	public String getTextKscpCladCodClasAdd() {
		return this.textKscpCladCodClasAdd;
	}

	public void setTextKscpCladCodClasAdd(String textKscpCladCodClasAdd) {
		this.textKscpCladCodClasAdd = textKscpCladCodClasAdd;
	}

	public String getDescKscpCladDescClasAdd() {
		return this.descKscpCladDescClasAdd;
	}

	public void setDescKscpCladDescClasAdd(String descKscpCladDescClasAdd) {
		this.descKscpCladDescClasAdd = descKscpCladDescClasAdd;
	}

	public String getTextKscpScpiIndirizzo() {
		return this.textKscpScpiIndirizzo;
	}

	public void setTextKscpScpiIndirizzo(String textKscpScpiIndirizzo) {
		this.textKscpScpiIndirizzo = textKscpScpiIndirizzo;
	}

	public String getNumeKscpScpiCap() {
		return this.numeKscpScpiCap;
	}

	public void setNumeKscpScpiCap(String numeKscpScpiCap) {
		this.numeKscpScpiCap = numeKscpScpiCap;
	}

}
