package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SwAnagraficaciganac generated by hbm2java
 */
public class SwAnagraficaciganac implements java.io.Serializable {

	private long sequSwAnagraficaciganac;
	private String textKsogSogCfiscaleStApp;
	private String textKsogSogDenStApp;
	private String textKsogSoggCfiscale;
	private String textKsogSoggDenominazione;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String codiKcigCcigCodCig;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String codiKregKregId;
	private String descKregKregDescRegione;
	private String textCodFonte;
	private String textCcupTipiCodTipInv;
	private String descKcigCgapOggettoGara;
	private String textKcigTipcCodTipoScelta;
	private String descKcigTipcTipoSceltaCon;
	private String textKcigCgapCodGara;
	private String textKcigTicoCodTipoContra;
	private String descKcigTicoTipoContratto;
	private String textKcigKcomCodComune;
	private String descKcigKcomDescComune;
	private String textKcigKprvCodProvincia;
	private String descKcigKprvDescProvincia;
	private String textKcigKzonCodZona;
	private String descKcigKzonDescZona;
	private BigDecimal impoFmpgImpBaseAsta;
	private Date dataKcigCcigDataScadOffer;
	private String descKcigCcigOggettoLotto;
	private String flagKcigCcigIndSubappalto;
	private String textKcigCcigTipoAppalto;

	public SwAnagraficaciganac() {
	}

	public SwAnagraficaciganac(long sequSwAnagraficaciganac) {
		this.sequSwAnagraficaciganac = sequSwAnagraficaciganac;
	}

	public SwAnagraficaciganac(long sequSwAnagraficaciganac,
			String textKsogSogCfiscaleStApp, String textKsogSogDenStApp,
			String textKsogSoggCfiscale, String textKsogSoggDenominazione,
			String textKsogFogiCodFormaGiur, String descKsogFogiDescFormaGiu,
			String codiCcupCcupAnagCcup, String codiKcigCcigCodCig,
			String textCcupSipiCodSetInv, String descCcupSipiDescSetCup,
			String textCcupSspiCodSsetInv, String descCcupSspiDescSsetCup,
			String textCcupCipiCodCatInv, String descCcupCipiDescCatCup,
			String codiKregKregId, String descKregKregDescRegione,
			String textCodFonte, String textCcupTipiCodTipInv,
			String descKcigCgapOggettoGara, String textKcigTipcCodTipoScelta,
			String descKcigTipcTipoSceltaCon, String textKcigCgapCodGara,
			String textKcigTicoCodTipoContra, String descKcigTicoTipoContratto,
			String textKcigKcomCodComune, String descKcigKcomDescComune,
			String textKcigKprvCodProvincia, String descKcigKprvDescProvincia,
			String textKcigKzonCodZona, String descKcigKzonDescZona,
			BigDecimal impoFmpgImpBaseAsta, Date dataKcigCcigDataScadOffer,
			String descKcigCcigOggettoLotto, String flagKcigCcigIndSubappalto,
			String textKcigCcigTipoAppalto) {
		this.sequSwAnagraficaciganac = sequSwAnagraficaciganac;
		this.textKsogSogCfiscaleStApp = textKsogSogCfiscaleStApp;
		this.textKsogSogDenStApp = textKsogSogDenStApp;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.codiKregKregId = codiKregKregId;
		this.descKregKregDescRegione = descKregKregDescRegione;
		this.textCodFonte = textCodFonte;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.descKcigCgapOggettoGara = descKcigCgapOggettoGara;
		this.textKcigTipcCodTipoScelta = textKcigTipcCodTipoScelta;
		this.descKcigTipcTipoSceltaCon = descKcigTipcTipoSceltaCon;
		this.textKcigCgapCodGara = textKcigCgapCodGara;
		this.textKcigTicoCodTipoContra = textKcigTicoCodTipoContra;
		this.descKcigTicoTipoContratto = descKcigTicoTipoContratto;
		this.textKcigKcomCodComune = textKcigKcomCodComune;
		this.descKcigKcomDescComune = descKcigKcomDescComune;
		this.textKcigKprvCodProvincia = textKcigKprvCodProvincia;
		this.descKcigKprvDescProvincia = descKcigKprvDescProvincia;
		this.textKcigKzonCodZona = textKcigKzonCodZona;
		this.descKcigKzonDescZona = descKcigKzonDescZona;
		this.impoFmpgImpBaseAsta = impoFmpgImpBaseAsta;
		this.dataKcigCcigDataScadOffer = dataKcigCcigDataScadOffer;
		this.descKcigCcigOggettoLotto = descKcigCcigOggettoLotto;
		this.flagKcigCcigIndSubappalto = flagKcigCcigIndSubappalto;
		this.textKcigCcigTipoAppalto = textKcigCcigTipoAppalto;
	}

	public long getSequSwAnagraficaciganac() {
		return this.sequSwAnagraficaciganac;
	}

	public void setSequSwAnagraficaciganac(long sequSwAnagraficaciganac) {
		this.sequSwAnagraficaciganac = sequSwAnagraficaciganac;
	}

	public String getTextKsogSogCfiscaleStApp() {
		return this.textKsogSogCfiscaleStApp;
	}

	public void setTextKsogSogCfiscaleStApp(String textKsogSogCfiscaleStApp) {
		this.textKsogSogCfiscaleStApp = textKsogSogCfiscaleStApp;
	}

	public String getTextKsogSogDenStApp() {
		return this.textKsogSogDenStApp;
	}

	public void setTextKsogSogDenStApp(String textKsogSogDenStApp) {
		this.textKsogSogDenStApp = textKsogSogDenStApp;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogSoggDenominazione() {
		return this.textKsogSoggDenominazione;
	}

	public void setTextKsogSoggDenominazione(String textKsogSoggDenominazione) {
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getCodiKcigCcigCodCig() {
		return this.codiKcigCcigCodCig;
	}

	public void setCodiKcigCcigCodCig(String codiKcigCcigCodCig) {
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getCodiKregKregId() {
		return this.codiKregKregId;
	}

	public void setCodiKregKregId(String codiKregKregId) {
		this.codiKregKregId = codiKregKregId;
	}

	public String getDescKregKregDescRegione() {
		return this.descKregKregDescRegione;
	}

	public void setDescKregKregDescRegione(String descKregKregDescRegione) {
		this.descKregKregDescRegione = descKregKregDescRegione;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getDescKcigCgapOggettoGara() {
		return this.descKcigCgapOggettoGara;
	}

	public void setDescKcigCgapOggettoGara(String descKcigCgapOggettoGara) {
		this.descKcigCgapOggettoGara = descKcigCgapOggettoGara;
	}

	public String getTextKcigTipcCodTipoScelta() {
		return this.textKcigTipcCodTipoScelta;
	}

	public void setTextKcigTipcCodTipoScelta(String textKcigTipcCodTipoScelta) {
		this.textKcigTipcCodTipoScelta = textKcigTipcCodTipoScelta;
	}

	public String getDescKcigTipcTipoSceltaCon() {
		return this.descKcigTipcTipoSceltaCon;
	}

	public void setDescKcigTipcTipoSceltaCon(String descKcigTipcTipoSceltaCon) {
		this.descKcigTipcTipoSceltaCon = descKcigTipcTipoSceltaCon;
	}

	public String getTextKcigCgapCodGara() {
		return this.textKcigCgapCodGara;
	}

	public void setTextKcigCgapCodGara(String textKcigCgapCodGara) {
		this.textKcigCgapCodGara = textKcigCgapCodGara;
	}

	public String getTextKcigTicoCodTipoContra() {
		return this.textKcigTicoCodTipoContra;
	}

	public void setTextKcigTicoCodTipoContra(String textKcigTicoCodTipoContra) {
		this.textKcigTicoCodTipoContra = textKcigTicoCodTipoContra;
	}

	public String getDescKcigTicoTipoContratto() {
		return this.descKcigTicoTipoContratto;
	}

	public void setDescKcigTicoTipoContratto(String descKcigTicoTipoContratto) {
		this.descKcigTicoTipoContratto = descKcigTicoTipoContratto;
	}

	public String getTextKcigKcomCodComune() {
		return this.textKcigKcomCodComune;
	}

	public void setTextKcigKcomCodComune(String textKcigKcomCodComune) {
		this.textKcigKcomCodComune = textKcigKcomCodComune;
	}

	public String getDescKcigKcomDescComune() {
		return this.descKcigKcomDescComune;
	}

	public void setDescKcigKcomDescComune(String descKcigKcomDescComune) {
		this.descKcigKcomDescComune = descKcigKcomDescComune;
	}

	public String getTextKcigKprvCodProvincia() {
		return this.textKcigKprvCodProvincia;
	}

	public void setTextKcigKprvCodProvincia(String textKcigKprvCodProvincia) {
		this.textKcigKprvCodProvincia = textKcigKprvCodProvincia;
	}

	public String getDescKcigKprvDescProvincia() {
		return this.descKcigKprvDescProvincia;
	}

	public void setDescKcigKprvDescProvincia(String descKcigKprvDescProvincia) {
		this.descKcigKprvDescProvincia = descKcigKprvDescProvincia;
	}

	public String getTextKcigKzonCodZona() {
		return this.textKcigKzonCodZona;
	}

	public void setTextKcigKzonCodZona(String textKcigKzonCodZona) {
		this.textKcigKzonCodZona = textKcigKzonCodZona;
	}

	public String getDescKcigKzonDescZona() {
		return this.descKcigKzonDescZona;
	}

	public void setDescKcigKzonDescZona(String descKcigKzonDescZona) {
		this.descKcigKzonDescZona = descKcigKzonDescZona;
	}

	public BigDecimal getImpoFmpgImpBaseAsta() {
		return this.impoFmpgImpBaseAsta;
	}

	public void setImpoFmpgImpBaseAsta(BigDecimal impoFmpgImpBaseAsta) {
		this.impoFmpgImpBaseAsta = impoFmpgImpBaseAsta;
	}

	public Date getDataKcigCcigDataScadOffer() {
		return this.dataKcigCcigDataScadOffer;
	}

	public void setDataKcigCcigDataScadOffer(Date dataKcigCcigDataScadOffer) {
		this.dataKcigCcigDataScadOffer = dataKcigCcigDataScadOffer;
	}

	public String getDescKcigCcigOggettoLotto() {
		return this.descKcigCcigOggettoLotto;
	}

	public void setDescKcigCcigOggettoLotto(String descKcigCcigOggettoLotto) {
		this.descKcigCcigOggettoLotto = descKcigCcigOggettoLotto;
	}

	public String getFlagKcigCcigIndSubappalto() {
		return this.flagKcigCcigIndSubappalto;
	}

	public void setFlagKcigCcigIndSubappalto(String flagKcigCcigIndSubappalto) {
		this.flagKcigCcigIndSubappalto = flagKcigCcigIndSubappalto;
	}

	public String getTextKcigCcigTipoAppalto() {
		return this.textKcigCcigTipoAppalto;
	}

	public void setTextKcigCcigTipoAppalto(String textKcigCcigTipoAppalto) {
		this.textKcigCcigTipoAppalto = textKcigCcigTipoAppalto;
	}

}
