package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

/**
 * SwCups generated by hbm2java
 */
public class SwCups implements java.io.Serializable {

	private long sequSwCups;
	private String codiKurpUrpiCodLocProg;
	private String descKurpUrpiTitoloProg;
	private String textKurpUrpiNoteProg;
	private String textKsogSoggCfiscale;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String descCcupCcupDescInt;
	private String textCcupNipiCodNaturaInv;
	private String descCcupNipiDescNaturaCup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String codiKregKregId;
	private String descKregKregDescRegione;
	private String textCodFonte;
	private String descDimensione;
	private String textCcupTipiCodTipInv;

	public SwCups() {
	}

	public SwCups(long sequSwCups) {
		this.sequSwCups = sequSwCups;
	}

	public SwCups(long sequSwCups, String codiKurpUrpiCodLocProg,
			String descKurpUrpiTitoloProg, String textKurpUrpiNoteProg,
			String textKsogSoggCfiscale, String textKsogFogiCodFormaGiur,
			String descKsogFogiDescFormaGiu, String codiCcupCcupAnagCcup,
			String descCcupCcupDescInt, String textCcupNipiCodNaturaInv,
			String descCcupNipiDescNaturaCup, String textCcupSipiCodSetInv,
			String descCcupSipiDescSetCup, String textCcupSspiCodSsetInv,
			String descCcupSspiDescSsetCup, String textCcupCipiCodCatInv,
			String descCcupCipiDescCatCup, String codiKregKregId,
			String descKregKregDescRegione, String textCodFonte,
			String descDimensione, String textCcupTipiCodTipInv) {
		this.sequSwCups = sequSwCups;
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
		this.descKurpUrpiTitoloProg = descKurpUrpiTitoloProg;
		this.textKurpUrpiNoteProg = textKurpUrpiNoteProg;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.descCcupCcupDescInt = descCcupCcupDescInt;
		this.textCcupNipiCodNaturaInv = textCcupNipiCodNaturaInv;
		this.descCcupNipiDescNaturaCup = descCcupNipiDescNaturaCup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.codiKregKregId = codiKregKregId;
		this.descKregKregDescRegione = descKregKregDescRegione;
		this.textCodFonte = textCodFonte;
		this.descDimensione = descDimensione;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public long getSequSwCups() {
		return this.sequSwCups;
	}

	public void setSequSwCups(long sequSwCups) {
		this.sequSwCups = sequSwCups;
	}

	public String getCodiKurpUrpiCodLocProg() {
		return this.codiKurpUrpiCodLocProg;
	}

	public void setCodiKurpUrpiCodLocProg(String codiKurpUrpiCodLocProg) {
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
	}

	public String getDescKurpUrpiTitoloProg() {
		return this.descKurpUrpiTitoloProg;
	}

	public void setDescKurpUrpiTitoloProg(String descKurpUrpiTitoloProg) {
		this.descKurpUrpiTitoloProg = descKurpUrpiTitoloProg;
	}

	public String getTextKurpUrpiNoteProg() {
		return this.textKurpUrpiNoteProg;
	}

	public void setTextKurpUrpiNoteProg(String textKurpUrpiNoteProg) {
		this.textKurpUrpiNoteProg = textKurpUrpiNoteProg;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getDescCcupCcupDescInt() {
		return this.descCcupCcupDescInt;
	}

	public void setDescCcupCcupDescInt(String descCcupCcupDescInt) {
		this.descCcupCcupDescInt = descCcupCcupDescInt;
	}

	public String getTextCcupNipiCodNaturaInv() {
		return this.textCcupNipiCodNaturaInv;
	}

	public void setTextCcupNipiCodNaturaInv(String textCcupNipiCodNaturaInv) {
		this.textCcupNipiCodNaturaInv = textCcupNipiCodNaturaInv;
	}

	public String getDescCcupNipiDescNaturaCup() {
		return this.descCcupNipiDescNaturaCup;
	}

	public void setDescCcupNipiDescNaturaCup(String descCcupNipiDescNaturaCup) {
		this.descCcupNipiDescNaturaCup = descCcupNipiDescNaturaCup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getCodiKregKregId() {
		return this.codiKregKregId;
	}

	public void setCodiKregKregId(String codiKregKregId) {
		this.codiKregKregId = codiKregKregId;
	}

	public String getDescKregKregDescRegione() {
		return this.descKregKregDescRegione;
	}

	public void setDescKregKregDescRegione(String descKregKregDescRegione) {
		this.descKregKregDescRegione = descKregKregDescRegione;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getDescDimensione() {
		return this.descDimensione;
	}

	public void setDescDimensione(String descDimensione) {
		this.descDimensione = descDimensione;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

}
