package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SwDettaglioesitiinvibatchmop generated by hbm2java
 */
public class SwDettaglioesitiinvibatchmop implements java.io.Serializable {

	private long sequSwDettesitiinvibatchmop;
	private String codiKanfAnfbCodiceFile;
	private String textKsogSoggCfiscale;
	private String textKsogSoggDenominazione;
	private Date dttmKanfAnfbDataRif;
	private Date dataFeefInvio;
	private String descKtefEsitoFile;
	private String textFeefTipoControllo;
	private String descKtefTefbDescTipoEsito;
	private String textFeefDescrRigaElab;
	private String descKtrfTrfbDescrTipoRec;
	private String descKtrfTsfbDescrSezione;

	public SwDettaglioesitiinvibatchmop() {
	}

	public SwDettaglioesitiinvibatchmop(long sequSwDettesitiinvibatchmop) {
		this.sequSwDettesitiinvibatchmop = sequSwDettesitiinvibatchmop;
	}

	public SwDettaglioesitiinvibatchmop(long sequSwDettesitiinvibatchmop,
			String codiKanfAnfbCodiceFile, String textKsogSoggCfiscale,
			String textKsogSoggDenominazione, Date dttmKanfAnfbDataRif,
			Date dataFeefInvio, String descKtefEsitoFile,
			String textFeefTipoControllo, String descKtefTefbDescTipoEsito,
			String textFeefDescrRigaElab, String descKtrfTrfbDescrTipoRec,
			String descKtrfTsfbDescrSezione) {
		this.sequSwDettesitiinvibatchmop = sequSwDettesitiinvibatchmop;
		this.codiKanfAnfbCodiceFile = codiKanfAnfbCodiceFile;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
		this.dttmKanfAnfbDataRif = dttmKanfAnfbDataRif;
		this.dataFeefInvio = dataFeefInvio;
		this.descKtefEsitoFile = descKtefEsitoFile;
		this.textFeefTipoControllo = textFeefTipoControllo;
		this.descKtefTefbDescTipoEsito = descKtefTefbDescTipoEsito;
		this.textFeefDescrRigaElab = textFeefDescrRigaElab;
		this.descKtrfTrfbDescrTipoRec = descKtrfTrfbDescrTipoRec;
		this.descKtrfTsfbDescrSezione = descKtrfTsfbDescrSezione;
	}

	public long getSequSwDettesitiinvibatchmop() {
		return this.sequSwDettesitiinvibatchmop;
	}

	public void setSequSwDettesitiinvibatchmop(long sequSwDettesitiinvibatchmop) {
		this.sequSwDettesitiinvibatchmop = sequSwDettesitiinvibatchmop;
	}

	public String getCodiKanfAnfbCodiceFile() {
		return this.codiKanfAnfbCodiceFile;
	}

	public void setCodiKanfAnfbCodiceFile(String codiKanfAnfbCodiceFile) {
		this.codiKanfAnfbCodiceFile = codiKanfAnfbCodiceFile;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogSoggDenominazione() {
		return this.textKsogSoggDenominazione;
	}

	public void setTextKsogSoggDenominazione(String textKsogSoggDenominazione) {
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
	}

	public Date getDttmKanfAnfbDataRif() {
		return this.dttmKanfAnfbDataRif;
	}

	public void setDttmKanfAnfbDataRif(Date dttmKanfAnfbDataRif) {
		this.dttmKanfAnfbDataRif = dttmKanfAnfbDataRif;
	}

	public Date getDataFeefInvio() {
		return this.dataFeefInvio;
	}

	public void setDataFeefInvio(Date dataFeefInvio) {
		this.dataFeefInvio = dataFeefInvio;
	}

	public String getDescKtefEsitoFile() {
		return this.descKtefEsitoFile;
	}

	public void setDescKtefEsitoFile(String descKtefEsitoFile) {
		this.descKtefEsitoFile = descKtefEsitoFile;
	}

	public String getTextFeefTipoControllo() {
		return this.textFeefTipoControllo;
	}

	public void setTextFeefTipoControllo(String textFeefTipoControllo) {
		this.textFeefTipoControllo = textFeefTipoControllo;
	}

	public String getDescKtefTefbDescTipoEsito() {
		return this.descKtefTefbDescTipoEsito;
	}

	public void setDescKtefTefbDescTipoEsito(String descKtefTefbDescTipoEsito) {
		this.descKtefTefbDescTipoEsito = descKtefTefbDescTipoEsito;
	}

	public String getTextFeefDescrRigaElab() {
		return this.textFeefDescrRigaElab;
	}

	public void setTextFeefDescrRigaElab(String textFeefDescrRigaElab) {
		this.textFeefDescrRigaElab = textFeefDescrRigaElab;
	}

	public String getDescKtrfTrfbDescrTipoRec() {
		return this.descKtrfTrfbDescrTipoRec;
	}

	public void setDescKtrfTrfbDescrTipoRec(String descKtrfTrfbDescrTipoRec) {
		this.descKtrfTrfbDescrTipoRec = descKtrfTrfbDescrTipoRec;
	}

	public String getDescKtrfTsfbDescrSezione() {
		return this.descKtrfTsfbDescrSezione;
	}

	public void setDescKtrfTsfbDescrSezione(String descKtrfTsfbDescrSezione) {
		this.descKtrfTsfbDescrSezione = descKtrfTsfbDescrSezione;
	}

}
