package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SwEsitiinviibatchmop generated by hbm2java
 */
public class SwEsitiinviibatchmop implements java.io.Serializable {

	private long sequSwEsitiinviibatchmop;
	private String textKsogSoggCfiscale;
	private String textKsogSoggDenominazione;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiKanfAnfbCodiceFile;
	private Date dttmKanfAnfbDataRif;
	private Date dataFeerInvio;
	private String descKtefTefbDescTipoEsito;

	public SwEsitiinviibatchmop() {
	}

	public SwEsitiinviibatchmop(long sequSwEsitiinviibatchmop) {
		this.sequSwEsitiinviibatchmop = sequSwEsitiinviibatchmop;
	}

	public SwEsitiinviibatchmop(long sequSwEsitiinviibatchmop,
			String textKsogSoggCfiscale, String textKsogSoggDenominazione,
			String textKsogFogiCodFormaGiur, String descKsogFogiDescFormaGiu,
			String codiKanfAnfbCodiceFile, Date dttmKanfAnfbDataRif,
			Date dataFeerInvio, String descKtefTefbDescTipoEsito) {
		this.sequSwEsitiinviibatchmop = sequSwEsitiinviibatchmop;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiKanfAnfbCodiceFile = codiKanfAnfbCodiceFile;
		this.dttmKanfAnfbDataRif = dttmKanfAnfbDataRif;
		this.dataFeerInvio = dataFeerInvio;
		this.descKtefTefbDescTipoEsito = descKtefTefbDescTipoEsito;
	}

	public long getSequSwEsitiinviibatchmop() {
		return this.sequSwEsitiinviibatchmop;
	}

	public void setSequSwEsitiinviibatchmop(long sequSwEsitiinviibatchmop) {
		this.sequSwEsitiinviibatchmop = sequSwEsitiinviibatchmop;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogSoggDenominazione() {
		return this.textKsogSoggDenominazione;
	}

	public void setTextKsogSoggDenominazione(String textKsogSoggDenominazione) {
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiKanfAnfbCodiceFile() {
		return this.codiKanfAnfbCodiceFile;
	}

	public void setCodiKanfAnfbCodiceFile(String codiKanfAnfbCodiceFile) {
		this.codiKanfAnfbCodiceFile = codiKanfAnfbCodiceFile;
	}

	public Date getDttmKanfAnfbDataRif() {
		return this.dttmKanfAnfbDataRif;
	}

	public void setDttmKanfAnfbDataRif(Date dttmKanfAnfbDataRif) {
		this.dttmKanfAnfbDataRif = dttmKanfAnfbDataRif;
	}

	public Date getDataFeerInvio() {
		return this.dataFeerInvio;
	}

	public void setDataFeerInvio(Date dataFeerInvio) {
		this.dataFeerInvio = dataFeerInvio;
	}

	public String getDescKtefTefbDescTipoEsito() {
		return this.descKtefTefbDescTipoEsito;
	}

	public void setDescKtefTefbDescTipoEsito(String descKtefTefbDescTipoEsito) {
		this.descKtefTefbDescTipoEsito = descKtefTefbDescTipoEsito;
	}

}
