package com.bruno.model;

import com.bruno.model.json.ImpegniJson;
import com.bruno.model.json.PagamentiJson;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

/**
 * SwImpegni generated by hbm2java
 */
public class SwImpegni implements java.io.Serializable {

	private SwImpegniId id;

	public SwImpegni() {
	}

	public SwImpegni(SwImpegniId id) {
		this.id = id;
	}

	public SwImpegniId getId() {
		return this.id;
	}

	public void setId(SwImpegniId id) {
		this.id = id;
	}
	
public ImpegniJson wrapperToJson(){
		
		ImpegniJson PJson = new ImpegniJson();
		
		
		return PJson;
	}

}
