package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SwIndicatori generated by hbm2java
 */
public class SwIndicatori implements java.io.Serializable {

	private long sequSwIndicatori;
	private String textKsogSoggCfiscale;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String codiKregKregId;
	private String descKregKregDescRegione;
	private String textCodFonte;
	private String descDimensione;
	private String textCcupTipiCodTipInv;
	private String codiKurpUrpiCodLocProg;
	private Character textKicoTiinCodTipIndicat;
	private String descKicoTiinDescTipIndica;
	private Integer numeKicoIndiCodIndicatore;
	private String descKicoIndiDescrizMisura;
	private BigDecimal impoFmipImpValProgIniz;
	private BigDecimal impoFmipImpValAggiornato;
	private BigDecimal impoFmipImpValImpegnato;
	private BigDecimal impoFmipImpValConcluso;
	private BigDecimal impoFmipImpValBaseline;

	public SwIndicatori() {
	}

	public SwIndicatori(long sequSwIndicatori) {
		this.sequSwIndicatori = sequSwIndicatori;
	}

	public SwIndicatori(long sequSwIndicatori, String textKsogSoggCfiscale,
			String textKsogFogiCodFormaGiur, String descKsogFogiDescFormaGiu,
			String codiCcupCcupAnagCcup, String textCcupSipiCodSetInv,
			String descCcupSipiDescSetCup, String textCcupSspiCodSsetInv,
			String descCcupSspiDescSsetCup, String textCcupCipiCodCatInv,
			String descCcupCipiDescCatCup, String codiKregKregId,
			String descKregKregDescRegione, String textCodFonte,
			String descDimensione, String textCcupTipiCodTipInv,
			String codiKurpUrpiCodLocProg, Character textKicoTiinCodTipIndicat,
			String descKicoTiinDescTipIndica,
			Integer numeKicoIndiCodIndicatore,
			String descKicoIndiDescrizMisura,
			BigDecimal impoFmipImpValProgIniz,
			BigDecimal impoFmipImpValAggiornato,
			BigDecimal impoFmipImpValImpegnato,
			BigDecimal impoFmipImpValConcluso, BigDecimal impoFmipImpValBaseline) {
		this.sequSwIndicatori = sequSwIndicatori;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.codiKregKregId = codiKregKregId;
		this.descKregKregDescRegione = descKregKregDescRegione;
		this.textCodFonte = textCodFonte;
		this.descDimensione = descDimensione;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
		this.textKicoTiinCodTipIndicat = textKicoTiinCodTipIndicat;
		this.descKicoTiinDescTipIndica = descKicoTiinDescTipIndica;
		this.numeKicoIndiCodIndicatore = numeKicoIndiCodIndicatore;
		this.descKicoIndiDescrizMisura = descKicoIndiDescrizMisura;
		this.impoFmipImpValProgIniz = impoFmipImpValProgIniz;
		this.impoFmipImpValAggiornato = impoFmipImpValAggiornato;
		this.impoFmipImpValImpegnato = impoFmipImpValImpegnato;
		this.impoFmipImpValConcluso = impoFmipImpValConcluso;
		this.impoFmipImpValBaseline = impoFmipImpValBaseline;
	}

	public long getSequSwIndicatori() {
		return this.sequSwIndicatori;
	}

	public void setSequSwIndicatori(long sequSwIndicatori) {
		this.sequSwIndicatori = sequSwIndicatori;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getCodiKregKregId() {
		return this.codiKregKregId;
	}

	public void setCodiKregKregId(String codiKregKregId) {
		this.codiKregKregId = codiKregKregId;
	}

	public String getDescKregKregDescRegione() {
		return this.descKregKregDescRegione;
	}

	public void setDescKregKregDescRegione(String descKregKregDescRegione) {
		this.descKregKregDescRegione = descKregKregDescRegione;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getDescDimensione() {
		return this.descDimensione;
	}

	public void setDescDimensione(String descDimensione) {
		this.descDimensione = descDimensione;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getCodiKurpUrpiCodLocProg() {
		return this.codiKurpUrpiCodLocProg;
	}

	public void setCodiKurpUrpiCodLocProg(String codiKurpUrpiCodLocProg) {
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
	}

	public Character getTextKicoTiinCodTipIndicat() {
		return this.textKicoTiinCodTipIndicat;
	}

	public void setTextKicoTiinCodTipIndicat(Character textKicoTiinCodTipIndicat) {
		this.textKicoTiinCodTipIndicat = textKicoTiinCodTipIndicat;
	}

	public String getDescKicoTiinDescTipIndica() {
		return this.descKicoTiinDescTipIndica;
	}

	public void setDescKicoTiinDescTipIndica(String descKicoTiinDescTipIndica) {
		this.descKicoTiinDescTipIndica = descKicoTiinDescTipIndica;
	}

	public Integer getNumeKicoIndiCodIndicatore() {
		return this.numeKicoIndiCodIndicatore;
	}

	public void setNumeKicoIndiCodIndicatore(Integer numeKicoIndiCodIndicatore) {
		this.numeKicoIndiCodIndicatore = numeKicoIndiCodIndicatore;
	}

	public String getDescKicoIndiDescrizMisura() {
		return this.descKicoIndiDescrizMisura;
	}

	public void setDescKicoIndiDescrizMisura(String descKicoIndiDescrizMisura) {
		this.descKicoIndiDescrizMisura = descKicoIndiDescrizMisura;
	}

	public BigDecimal getImpoFmipImpValProgIniz() {
		return this.impoFmipImpValProgIniz;
	}

	public void setImpoFmipImpValProgIniz(BigDecimal impoFmipImpValProgIniz) {
		this.impoFmipImpValProgIniz = impoFmipImpValProgIniz;
	}

	public BigDecimal getImpoFmipImpValAggiornato() {
		return this.impoFmipImpValAggiornato;
	}

	public void setImpoFmipImpValAggiornato(BigDecimal impoFmipImpValAggiornato) {
		this.impoFmipImpValAggiornato = impoFmipImpValAggiornato;
	}

	public BigDecimal getImpoFmipImpValImpegnato() {
		return this.impoFmipImpValImpegnato;
	}

	public void setImpoFmipImpValImpegnato(BigDecimal impoFmipImpValImpegnato) {
		this.impoFmipImpValImpegnato = impoFmipImpValImpegnato;
	}

	public BigDecimal getImpoFmipImpValConcluso() {
		return this.impoFmipImpValConcluso;
	}

	public void setImpoFmipImpValConcluso(BigDecimal impoFmipImpValConcluso) {
		this.impoFmipImpValConcluso = impoFmipImpValConcluso;
	}

	public BigDecimal getImpoFmipImpValBaseline() {
		return this.impoFmipImpValBaseline;
	}

	public void setImpoFmipImpValBaseline(BigDecimal impoFmipImpValBaseline) {
		this.impoFmipImpValBaseline = impoFmipImpValBaseline;
	}

}
