package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

/**
 * SwLocalizzazioni generated by hbm2java
 */
public class SwLocalizzazioni implements java.io.Serializable {

	private long sequSwLocalizzazioni;
	private String textKsogSoggCfiscale;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String textCcupNipiCodNaturaInv;
	private String descCcupNipiDescNaturaCup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String textCodFonte;
	private String descDimensione;
	private String textCcupTipiCodTipInv;
	private String codiKurpUrpiCodLocProg;
	private String codiKregKregId;
	private String descKregKregDescRegione;
	private String codiKprvKprvCodProvincia;
	private String textKprvKprvDescProvincia;
	private String codiKcomKcomId;
	private String textKcomKcomDescComune;

	public SwLocalizzazioni() {
	}

	public SwLocalizzazioni(long sequSwLocalizzazioni) {
		this.sequSwLocalizzazioni = sequSwLocalizzazioni;
	}

	public SwLocalizzazioni(long sequSwLocalizzazioni,
			String textKsogSoggCfiscale, String textKsogFogiCodFormaGiur,
			String descKsogFogiDescFormaGiu, String codiCcupCcupAnagCcup,
			String textCcupNipiCodNaturaInv, String descCcupNipiDescNaturaCup,
			String textCcupSipiCodSetInv, String descCcupSipiDescSetCup,
			String textCcupSspiCodSsetInv, String descCcupSspiDescSsetCup,
			String textCcupCipiCodCatInv, String descCcupCipiDescCatCup,
			String textCodFonte, String descDimensione,
			String textCcupTipiCodTipInv, String codiKurpUrpiCodLocProg,
			String codiKregKregId, String descKregKregDescRegione,
			String codiKprvKprvCodProvincia, String textKprvKprvDescProvincia,
			String codiKcomKcomId, String textKcomKcomDescComune) {
		this.sequSwLocalizzazioni = sequSwLocalizzazioni;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.textCcupNipiCodNaturaInv = textCcupNipiCodNaturaInv;
		this.descCcupNipiDescNaturaCup = descCcupNipiDescNaturaCup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.textCodFonte = textCodFonte;
		this.descDimensione = descDimensione;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
		this.codiKregKregId = codiKregKregId;
		this.descKregKregDescRegione = descKregKregDescRegione;
		this.codiKprvKprvCodProvincia = codiKprvKprvCodProvincia;
		this.textKprvKprvDescProvincia = textKprvKprvDescProvincia;
		this.codiKcomKcomId = codiKcomKcomId;
		this.textKcomKcomDescComune = textKcomKcomDescComune;
	}

	public long getSequSwLocalizzazioni() {
		return this.sequSwLocalizzazioni;
	}

	public void setSequSwLocalizzazioni(long sequSwLocalizzazioni) {
		this.sequSwLocalizzazioni = sequSwLocalizzazioni;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getTextCcupNipiCodNaturaInv() {
		return this.textCcupNipiCodNaturaInv;
	}

	public void setTextCcupNipiCodNaturaInv(String textCcupNipiCodNaturaInv) {
		this.textCcupNipiCodNaturaInv = textCcupNipiCodNaturaInv;
	}

	public String getDescCcupNipiDescNaturaCup() {
		return this.descCcupNipiDescNaturaCup;
	}

	public void setDescCcupNipiDescNaturaCup(String descCcupNipiDescNaturaCup) {
		this.descCcupNipiDescNaturaCup = descCcupNipiDescNaturaCup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getDescDimensione() {
		return this.descDimensione;
	}

	public void setDescDimensione(String descDimensione) {
		this.descDimensione = descDimensione;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getCodiKurpUrpiCodLocProg() {
		return this.codiKurpUrpiCodLocProg;
	}

	public void setCodiKurpUrpiCodLocProg(String codiKurpUrpiCodLocProg) {
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
	}

	public String getCodiKregKregId() {
		return this.codiKregKregId;
	}

	public void setCodiKregKregId(String codiKregKregId) {
		this.codiKregKregId = codiKregKregId;
	}

	public String getDescKregKregDescRegione() {
		return this.descKregKregDescRegione;
	}

	public void setDescKregKregDescRegione(String descKregKregDescRegione) {
		this.descKregKregDescRegione = descKregKregDescRegione;
	}

	public String getCodiKprvKprvCodProvincia() {
		return this.codiKprvKprvCodProvincia;
	}

	public void setCodiKprvKprvCodProvincia(String codiKprvKprvCodProvincia) {
		this.codiKprvKprvCodProvincia = codiKprvKprvCodProvincia;
	}

	public String getTextKprvKprvDescProvincia() {
		return this.textKprvKprvDescProvincia;
	}

	public void setTextKprvKprvDescProvincia(String textKprvKprvDescProvincia) {
		this.textKprvKprvDescProvincia = textKprvKprvDescProvincia;
	}

	public String getCodiKcomKcomId() {
		return this.codiKcomKcomId;
	}

	public void setCodiKcomKcomId(String codiKcomKcomId) {
		this.codiKcomKcomId = codiKcomKcomId;
	}

	public String getTextKcomKcomDescComune() {
		return this.textKcomKcomDescComune;
	}

	public void setTextKcomKcomDescComune(String textKcomKcomDescComune) {
		this.textKcomKcomDescComune = textKcomKcomDescComune;
	}

}
