package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import com.bruno.model.json.PagamentoJson;

/**
 * SwPagamenti generated by hbm2java
 */
public class Swpagamenti implements java.io.Serializable {

	private long sequSwPagamento;
	private String textKsogSoggCfiscale;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String codiKregKregId;
	private String descKregKregDescRegione;
	private String textCodFonte;
	private String descDimensione;
	private String textCcupTipiCodTipInv;
	private String codLocProg;
	private Date dataPagamento;
	private String codicePagamento;
	private String tipologiaPagamento;
	private BigDecimal importo;
	private String codiceCausale;
	private String descrizioneCausale;
	private String codiCgelCgelId;
	private String descCgelCgelDescGest;
	private String codiceGestionale;
	private String descCodiceGestionale;
	private String note;

	public Swpagamenti() {
	}

	public Swpagamenti(long sequSwPagamento) {
		this.sequSwPagamento = sequSwPagamento;
	}

	public String getTextKsogSoggCfiscale() {
		return textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getTextCcupSipiCodSetInv() {
		return textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupCipiCodCatInv() {
		return textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getCodiKregKregId() {
		return codiKregKregId;
	}

	public void setCodiKregKregId(String codiKregKregId) {
		this.codiKregKregId = codiKregKregId;
	}

	public String getDescKregKregDescRegione() {
		return descKregKregDescRegione;
	}

	public void setDescKregKregDescRegione(String descKregKregDescRegione) {
		this.descKregKregDescRegione = descKregKregDescRegione;
	}

	public String getTextCodFonte() {
		return textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getDescDimensione() {
		return descDimensione;
	}

	public void setDescDimensione(String descDimensione) {
		this.descDimensione = descDimensione;
	}

	public String getTextCcupTipiCodTipInv() {
		return textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getCodLocProg() {
		return codLocProg;
	}

	public void setCodLocProg(String codLocProg) {
		this.codLocProg = codLocProg;
	}

	public Date getDataPagamento() {
		return dataPagamento;
	}

	public void setDataPagamento(Date dataPagamento) {
		this.dataPagamento = dataPagamento;
	}

	public String getCodicePagamento() {
		return codicePagamento;
	}

	public void setCodicePagamento(String codicePagamento) {
		this.codicePagamento = codicePagamento;
	}

	public String getTipologiaPagamento() {
		return tipologiaPagamento;
	}

	public void setTipologiaPagamento(String tipologiaPagamento) {
		this.tipologiaPagamento = tipologiaPagamento;
	}

	public BigDecimal getImporto() {
		return importo;
	}

	public void setImporto(BigDecimal importo) {
		this.importo = importo;
	}

	public String getCodiceCausale() {
		return codiceCausale;
	}

	public void setCodiceCausale(String codiceCausale) {
		this.codiceCausale = codiceCausale;
	}

	public String getDescrizioneCausale() {
		return descrizioneCausale;
	}

	public void setDescrizioneCausale(String descrizioneCausale) {
		this.descrizioneCausale = descrizioneCausale;
	}

	public String getCodiCgelCgelId() {
		return codiCgelCgelId;
	}

	public void setCodiCgelCgelId(String codiCgelCgelId) {
		this.codiCgelCgelId = codiCgelCgelId;
	}

	public String getDescCgelCgelDescGest() {
		return descCgelCgelDescGest;
	}

	public void setDescCgelCgelDescGest(String descCgelCgelDescGest) {
		this.descCgelCgelDescGest = descCgelCgelDescGest;
	}

	public String getCodiceGestionale() {
		return codiceGestionale;
	}

	public void setCodiceGestionale(String codiceGestionale) {
		this.codiceGestionale = codiceGestionale;
	}

	public String getDescCodiceGestionale() {
		return descCodiceGestionale;
	}

	public void setDescCodiceGestionale(String descCodiceGestionale) {
		this.descCodiceGestionale = descCodiceGestionale;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public long getSequSwPagamento() {
		return sequSwPagamento;
	}

	public void setSequSwPagamento(long sequSwPagamento) {
		this.sequSwPagamento = sequSwPagamento;
	}
	
	public PagamentoJson wrapperToJson(){
		
		PagamentoJson PJson = new PagamentoJson();
		PJson.setCodLocProg(this.codLocProg);
		PJson.setCodicePagamento(this.codicePagamento);
		PJson.setDataPagamento(this.dataPagamento);
		PJson.setImporto(this.importo);
		PJson.setTipologiaPagamento(this.tipologiaPagamento);
		PJson.setCodiceCausale(this.codiceCausale);
		PJson.setDescrizioneCausale(this.descrizioneCausale);
		PJson.setCodiceGestionale(this.codiceGestionale);
		PJson.setDescCodiceGestionale(this.descCodiceGestionale);
		PJson.setNote(this.note);
		return PJson;
	}
	
}
