package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SwProceduraaggiudicazioneanac generated by hbm2java
 */
public class SwProceduraaggiudicazioneanac implements java.io.Serializable {

	private long sequSwProceduraaggiudanac;
	private String textKsogSogCfiscaleStApp;
	private String textKsogSogDenStApp;
	private String textKsogSoggCfiscale;
	private String textKsogSoggDenominazione;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiKcigCcigCodCig;
	private String codiCcupCcupAnagCcup;
	private String descCcupCcupDescInt;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textKcigKregCodRegione;
	private String descKcigKregDescRegione;
	private String textCodFonte;
	private String textCcupTipiCodTipInv;
	private Date impoFmpgDataOfferta;
	private Date impoFmpgDataAggiudic;
	private BigDecimal impoFmpgImpBaseAsta;
	private BigDecimal impoFmpgImportoAggiud;
	private BigDecimal percFmpgPercentualeOff;

	public SwProceduraaggiudicazioneanac() {
	}

	public SwProceduraaggiudicazioneanac(long sequSwProceduraaggiudanac) {
		this.sequSwProceduraaggiudanac = sequSwProceduraaggiudanac;
	}

	public SwProceduraaggiudicazioneanac(long sequSwProceduraaggiudanac,
			String textKsogSogCfiscaleStApp, String textKsogSogDenStApp,
			String textKsogSoggCfiscale, String textKsogSoggDenominazione,
			String textKsogFogiCodFormaGiur, String descKsogFogiDescFormaGiu,
			String codiKcigCcigCodCig, String codiCcupCcupAnagCcup,
			String descCcupCcupDescInt, String textCcupCipiCodCatInv,
			String descCcupCipiDescCatCup, String textCcupSspiCodSsetInv,
			String descCcupSspiDescSsetCup, String textCcupSipiCodSetInv,
			String descCcupSipiDescSetCup, String textKcigKregCodRegione,
			String descKcigKregDescRegione, String textCodFonte,
			String textCcupTipiCodTipInv, Date impoFmpgDataOfferta,
			Date impoFmpgDataAggiudic, BigDecimal impoFmpgImpBaseAsta,
			BigDecimal impoFmpgImportoAggiud, BigDecimal percFmpgPercentualeOff) {
		this.sequSwProceduraaggiudanac = sequSwProceduraaggiudanac;
		this.textKsogSogCfiscaleStApp = textKsogSogCfiscaleStApp;
		this.textKsogSogDenStApp = textKsogSogDenStApp;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.descCcupCcupDescInt = descCcupCcupDescInt;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textKcigKregCodRegione = textKcigKregCodRegione;
		this.descKcigKregDescRegione = descKcigKregDescRegione;
		this.textCodFonte = textCodFonte;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.impoFmpgDataOfferta = impoFmpgDataOfferta;
		this.impoFmpgDataAggiudic = impoFmpgDataAggiudic;
		this.impoFmpgImpBaseAsta = impoFmpgImpBaseAsta;
		this.impoFmpgImportoAggiud = impoFmpgImportoAggiud;
		this.percFmpgPercentualeOff = percFmpgPercentualeOff;
	}

	public long getSequSwProceduraaggiudanac() {
		return this.sequSwProceduraaggiudanac;
	}

	public void setSequSwProceduraaggiudanac(long sequSwProceduraaggiudanac) {
		this.sequSwProceduraaggiudanac = sequSwProceduraaggiudanac;
	}

	public String getTextKsogSogCfiscaleStApp() {
		return this.textKsogSogCfiscaleStApp;
	}

	public void setTextKsogSogCfiscaleStApp(String textKsogSogCfiscaleStApp) {
		this.textKsogSogCfiscaleStApp = textKsogSogCfiscaleStApp;
	}

	public String getTextKsogSogDenStApp() {
		return this.textKsogSogDenStApp;
	}

	public void setTextKsogSogDenStApp(String textKsogSogDenStApp) {
		this.textKsogSogDenStApp = textKsogSogDenStApp;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogSoggDenominazione() {
		return this.textKsogSoggDenominazione;
	}

	public void setTextKsogSoggDenominazione(String textKsogSoggDenominazione) {
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiKcigCcigCodCig() {
		return this.codiKcigCcigCodCig;
	}

	public void setCodiKcigCcigCodCig(String codiKcigCcigCodCig) {
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getDescCcupCcupDescInt() {
		return this.descCcupCcupDescInt;
	}

	public void setDescCcupCcupDescInt(String descCcupCcupDescInt) {
		this.descCcupCcupDescInt = descCcupCcupDescInt;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextKcigKregCodRegione() {
		return this.textKcigKregCodRegione;
	}

	public void setTextKcigKregCodRegione(String textKcigKregCodRegione) {
		this.textKcigKregCodRegione = textKcigKregCodRegione;
	}

	public String getDescKcigKregDescRegione() {
		return this.descKcigKregDescRegione;
	}

	public void setDescKcigKregDescRegione(String descKcigKregDescRegione) {
		this.descKcigKregDescRegione = descKcigKregDescRegione;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public Date getImpoFmpgDataOfferta() {
		return this.impoFmpgDataOfferta;
	}

	public void setImpoFmpgDataOfferta(Date impoFmpgDataOfferta) {
		this.impoFmpgDataOfferta = impoFmpgDataOfferta;
	}

	public Date getImpoFmpgDataAggiudic() {
		return this.impoFmpgDataAggiudic;
	}

	public void setImpoFmpgDataAggiudic(Date impoFmpgDataAggiudic) {
		this.impoFmpgDataAggiudic = impoFmpgDataAggiudic;
	}

	public BigDecimal getImpoFmpgImpBaseAsta() {
		return this.impoFmpgImpBaseAsta;
	}

	public void setImpoFmpgImpBaseAsta(BigDecimal impoFmpgImpBaseAsta) {
		this.impoFmpgImpBaseAsta = impoFmpgImpBaseAsta;
	}

	public BigDecimal getImpoFmpgImportoAggiud() {
		return this.impoFmpgImportoAggiud;
	}

	public void setImpoFmpgImportoAggiud(BigDecimal impoFmpgImportoAggiud) {
		this.impoFmpgImportoAggiud = impoFmpgImportoAggiud;
	}

	public BigDecimal getPercFmpgPercentualeOff() {
		return this.percFmpgPercentualeOff;
	}

	public void setPercFmpgPercentualeOff(BigDecimal percFmpgPercentualeOff) {
		this.percFmpgPercentualeOff = percFmpgPercentualeOff;
	}

}
