package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

/**
 * SwRevocherinunce generated by hbm2java
 */
public class SwRevocherinunce implements java.io.Serializable {

	private SwRevocherinunceId id;

	public SwRevocherinunce() {
	}

	public SwRevocherinunce(SwRevocherinunceId id) {
		this.id = id;
	}

	public SwRevocherinunceId getId() {
		return this.id;
	}

	public void setId(SwRevocherinunceId id) {
		this.id = id;
	}

}
