package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SwSalanac generated by hbm2java
 */
public class SwSalanac implements java.io.Serializable {

	private long sequSwSalanac;
	private String textKsogSogCfiscaleStApp;
	private String textKsogSogDenStApp;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String codiKcigCcigCodCig;
	private String textKsogSoggCfiscale;
	private String textKsogSoggDenominazione;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textKcigKregCodRegione;
	private String descKcigKregDescRegione;
	private String textCodFonte;
	private String textCcupTipiCodTipInv;
	private Date dataFmpgSal;
	private BigDecimal impoFmpgImpDocumStep;

	public SwSalanac() {
	}

	public SwSalanac(long sequSwSalanac) {
		this.sequSwSalanac = sequSwSalanac;
	}

	public SwSalanac(long sequSwSalanac, String textKsogSogCfiscaleStApp,
			String textKsogSogDenStApp, String textKsogFogiCodFormaGiur,
			String descKsogFogiDescFormaGiu, String codiCcupCcupAnagCcup,
			String codiKcigCcigCodCig, String textKsogSoggCfiscale,
			String textKsogSoggDenominazione, String textCcupCipiCodCatInv,
			String descCcupCipiDescCatCup, String textCcupSspiCodSsetInv,
			String descCcupSspiDescSsetCup, String textCcupSipiCodSetInv,
			String descCcupSipiDescSetCup, String textKcigKregCodRegione,
			String descKcigKregDescRegione, String textCodFonte,
			String textCcupTipiCodTipInv, Date dataFmpgSal,
			BigDecimal impoFmpgImpDocumStep) {
		this.sequSwSalanac = sequSwSalanac;
		this.textKsogSogCfiscaleStApp = textKsogSogCfiscaleStApp;
		this.textKsogSogDenStApp = textKsogSogDenStApp;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textKcigKregCodRegione = textKcigKregCodRegione;
		this.descKcigKregDescRegione = descKcigKregDescRegione;
		this.textCodFonte = textCodFonte;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.dataFmpgSal = dataFmpgSal;
		this.impoFmpgImpDocumStep = impoFmpgImpDocumStep;
	}

	public long getSequSwSalanac() {
		return this.sequSwSalanac;
	}

	public void setSequSwSalanac(long sequSwSalanac) {
		this.sequSwSalanac = sequSwSalanac;
	}

	public String getTextKsogSogCfiscaleStApp() {
		return this.textKsogSogCfiscaleStApp;
	}

	public void setTextKsogSogCfiscaleStApp(String textKsogSogCfiscaleStApp) {
		this.textKsogSogCfiscaleStApp = textKsogSogCfiscaleStApp;
	}

	public String getTextKsogSogDenStApp() {
		return this.textKsogSogDenStApp;
	}

	public void setTextKsogSogDenStApp(String textKsogSogDenStApp) {
		this.textKsogSogDenStApp = textKsogSogDenStApp;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getCodiKcigCcigCodCig() {
		return this.codiKcigCcigCodCig;
	}

	public void setCodiKcigCcigCodCig(String codiKcigCcigCodCig) {
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogSoggDenominazione() {
		return this.textKsogSoggDenominazione;
	}

	public void setTextKsogSoggDenominazione(String textKsogSoggDenominazione) {
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextKcigKregCodRegione() {
		return this.textKcigKregCodRegione;
	}

	public void setTextKcigKregCodRegione(String textKcigKregCodRegione) {
		this.textKcigKregCodRegione = textKcigKregCodRegione;
	}

	public String getDescKcigKregDescRegione() {
		return this.descKcigKregDescRegione;
	}

	public void setDescKcigKregDescRegione(String descKcigKregDescRegione) {
		this.descKcigKregDescRegione = descKcigKregDescRegione;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public Date getDataFmpgSal() {
		return this.dataFmpgSal;
	}

	public void setDataFmpgSal(Date dataFmpgSal) {
		this.dataFmpgSal = dataFmpgSal;
	}

	public BigDecimal getImpoFmpgImpDocumStep() {
		return this.impoFmpgImpDocumStep;
	}

	public void setImpoFmpgImpDocumStep(BigDecimal impoFmpgImpDocumStep) {
		this.impoFmpgImpDocumStep = impoFmpgImpDocumStep;
	}

}
