package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SwSal generated by hbm2java
 */
public class SwSal implements java.io.Serializable {

	private long sequSwSal;
	private String textKsogSoggCfiscale;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String codiKregKregId;
	private String descKregKregDescRegione;
	private String textCodFonte;
	private String descDimensione;
	private String textCcupTipiCodTipInv;
	private String codiKurpUrpiCodLocProg;
	private String codiKcigCcigCodCig;
	private Integer numeFsalProgressivoSal;
	private String descFsalDescrizioneSal;
	private Date dataFsalEmissSal;
	private BigDecimal impoFsalImportoSal;
	private String textFsalNoteSal;

	public SwSal() {
	}

	public SwSal(long sequSwSal) {
		this.sequSwSal = sequSwSal;
	}

	public SwSal(long sequSwSal, String textKsogSoggCfiscale,
			String textKsogFogiCodFormaGiur, String descKsogFogiDescFormaGiu,
			String codiCcupCcupAnagCcup, String textCcupSipiCodSetInv,
			String descCcupSipiDescSetCup, String textCcupSspiCodSsetInv,
			String descCcupSspiDescSsetCup, String textCcupCipiCodCatInv,
			String descCcupCipiDescCatCup, String codiKregKregId,
			String descKregKregDescRegione, String textCodFonte,
			String descDimensione, String textCcupTipiCodTipInv,
			String codiKurpUrpiCodLocProg, String codiKcigCcigCodCig,
			Integer numeFsalProgressivoSal, String descFsalDescrizioneSal,
			Date dataFsalEmissSal, BigDecimal impoFsalImportoSal,
			String textFsalNoteSal) {
		this.sequSwSal = sequSwSal;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.codiKregKregId = codiKregKregId;
		this.descKregKregDescRegione = descKregKregDescRegione;
		this.textCodFonte = textCodFonte;
		this.descDimensione = descDimensione;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
		this.numeFsalProgressivoSal = numeFsalProgressivoSal;
		this.descFsalDescrizioneSal = descFsalDescrizioneSal;
		this.dataFsalEmissSal = dataFsalEmissSal;
		this.impoFsalImportoSal = impoFsalImportoSal;
		this.textFsalNoteSal = textFsalNoteSal;
	}

	public long getSequSwSal() {
		return this.sequSwSal;
	}

	public void setSequSwSal(long sequSwSal) {
		this.sequSwSal = sequSwSal;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getCodiKregKregId() {
		return this.codiKregKregId;
	}

	public void setCodiKregKregId(String codiKregKregId) {
		this.codiKregKregId = codiKregKregId;
	}

	public String getDescKregKregDescRegione() {
		return this.descKregKregDescRegione;
	}

	public void setDescKregKregDescRegione(String descKregKregDescRegione) {
		this.descKregKregDescRegione = descKregKregDescRegione;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getDescDimensione() {
		return this.descDimensione;
	}

	public void setDescDimensione(String descDimensione) {
		this.descDimensione = descDimensione;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getCodiKurpUrpiCodLocProg() {
		return this.codiKurpUrpiCodLocProg;
	}

	public void setCodiKurpUrpiCodLocProg(String codiKurpUrpiCodLocProg) {
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
	}

	public String getCodiKcigCcigCodCig() {
		return this.codiKcigCcigCodCig;
	}

	public void setCodiKcigCcigCodCig(String codiKcigCcigCodCig) {
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
	}

	public Integer getNumeFsalProgressivoSal() {
		return this.numeFsalProgressivoSal;
	}

	public void setNumeFsalProgressivoSal(Integer numeFsalProgressivoSal) {
		this.numeFsalProgressivoSal = numeFsalProgressivoSal;
	}

	public String getDescFsalDescrizioneSal() {
		return this.descFsalDescrizioneSal;
	}

	public void setDescFsalDescrizioneSal(String descFsalDescrizioneSal) {
		this.descFsalDescrizioneSal = descFsalDescrizioneSal;
	}

	public Date getDataFsalEmissSal() {
		return this.dataFsalEmissSal;
	}

	public void setDataFsalEmissSal(Date dataFsalEmissSal) {
		this.dataFsalEmissSal = dataFsalEmissSal;
	}

	public BigDecimal getImpoFsalImportoSal() {
		return this.impoFsalImportoSal;
	}

	public void setImpoFsalImportoSal(BigDecimal impoFsalImportoSal) {
		this.impoFsalImportoSal = impoFsalImportoSal;
	}

	public String getTextFsalNoteSal() {
		return this.textFsalNoteSal;
	}

	public void setTextFsalNoteSal(String textFsalNoteSal) {
		this.textFsalNoteSal = textFsalNoteSal;
	}

}
