package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

/**
 * SwSospensioni generated by hbm2java
 */
public class SwSospensioni implements java.io.Serializable {

	private SwSospensioniId id;

	public SwSospensioni() {
	}

	public SwSospensioni(SwSospensioniId id) {
		this.id = id;
	}

	public SwSospensioniId getId() {
		return this.id;
	}

	public void setId(SwSospensioniId id) {
		this.id = id;
	}

}
