package com.bruno.model;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SwVarianticontrattoanac generated by hbm2java
 */
public class SwVarianticontrattoanac implements java.io.Serializable {

	private long sequSwVarianticontrattoanac;
	private String textKsogSogCfiscaleStApp;
	private String textKsogSogDenStApp;
	private String textKsogSoggCfiscale;
	private String textKsogSoggDenominazione;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiKcigCcigCodCig;
	private String codiCcupCcupAnagCcup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String textKcigKregCodRegione;
	private String descKcigKregDescRegione;
	private String textCodFonte;
	private String textCcupTipiCodTipInv;
	private String codiFmpgCodDocumento;
	private String descFmpgOggettoDocum;
	private String textKcigTicoCodTipoContra;
	private String descKcigTicoTipoContratto;
	private Date dataFmpgVariante;
	private BigDecimal impoFmpgImpVariaAumento;
	private BigDecimal impoFmpgImpVariaDimin;
	private BigDecimal numFmpgNumeGiorniVar;

	public SwVarianticontrattoanac() {
	}

	public SwVarianticontrattoanac(long sequSwVarianticontrattoanac) {
		this.sequSwVarianticontrattoanac = sequSwVarianticontrattoanac;
	}

	public SwVarianticontrattoanac(long sequSwVarianticontrattoanac,
			String textKsogSogCfiscaleStApp, String textKsogSogDenStApp,
			String textKsogSoggCfiscale, String textKsogSoggDenominazione,
			String textKsogFogiCodFormaGiur, String descKsogFogiDescFormaGiu,
			String codiKcigCcigCodCig, String codiCcupCcupAnagCcup,
			String textCcupSipiCodSetInv, String descCcupSipiDescSetCup,
			String textCcupSspiCodSsetInv, String descCcupSspiDescSsetCup,
			String textCcupCipiCodCatInv, String descCcupCipiDescCatCup,
			String textKcigKregCodRegione, String descKcigKregDescRegione,
			String textCodFonte, String textCcupTipiCodTipInv,
			String codiFmpgCodDocumento, String descFmpgOggettoDocum,
			String textKcigTicoCodTipoContra, String descKcigTicoTipoContratto,
			Date dataFmpgVariante, BigDecimal impoFmpgImpVariaAumento,
			BigDecimal impoFmpgImpVariaDimin, BigDecimal numFmpgNumeGiorniVar) {
		this.sequSwVarianticontrattoanac = sequSwVarianticontrattoanac;
		this.textKsogSogCfiscaleStApp = textKsogSogCfiscaleStApp;
		this.textKsogSogDenStApp = textKsogSogDenStApp;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.textKcigKregCodRegione = textKcigKregCodRegione;
		this.descKcigKregDescRegione = descKcigKregDescRegione;
		this.textCodFonte = textCodFonte;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.codiFmpgCodDocumento = codiFmpgCodDocumento;
		this.descFmpgOggettoDocum = descFmpgOggettoDocum;
		this.textKcigTicoCodTipoContra = textKcigTicoCodTipoContra;
		this.descKcigTicoTipoContratto = descKcigTicoTipoContratto;
		this.dataFmpgVariante = dataFmpgVariante;
		this.impoFmpgImpVariaAumento = impoFmpgImpVariaAumento;
		this.impoFmpgImpVariaDimin = impoFmpgImpVariaDimin;
		this.numFmpgNumeGiorniVar = numFmpgNumeGiorniVar;
	}

	public long getSequSwVarianticontrattoanac() {
		return this.sequSwVarianticontrattoanac;
	}

	public void setSequSwVarianticontrattoanac(long sequSwVarianticontrattoanac) {
		this.sequSwVarianticontrattoanac = sequSwVarianticontrattoanac;
	}

	public String getTextKsogSogCfiscaleStApp() {
		return this.textKsogSogCfiscaleStApp;
	}

	public void setTextKsogSogCfiscaleStApp(String textKsogSogCfiscaleStApp) {
		this.textKsogSogCfiscaleStApp = textKsogSogCfiscaleStApp;
	}

	public String getTextKsogSogDenStApp() {
		return this.textKsogSogDenStApp;
	}

	public void setTextKsogSogDenStApp(String textKsogSogDenStApp) {
		this.textKsogSogDenStApp = textKsogSogDenStApp;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogSoggDenominazione() {
		return this.textKsogSoggDenominazione;
	}

	public void setTextKsogSoggDenominazione(String textKsogSoggDenominazione) {
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiKcigCcigCodCig() {
		return this.codiKcigCcigCodCig;
	}

	public void setCodiKcigCcigCodCig(String codiKcigCcigCodCig) {
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getTextKcigKregCodRegione() {
		return this.textKcigKregCodRegione;
	}

	public void setTextKcigKregCodRegione(String textKcigKregCodRegione) {
		this.textKcigKregCodRegione = textKcigKregCodRegione;
	}

	public String getDescKcigKregDescRegione() {
		return this.descKcigKregDescRegione;
	}

	public void setDescKcigKregDescRegione(String descKcigKregDescRegione) {
		this.descKcigKregDescRegione = descKcigKregDescRegione;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getCodiFmpgCodDocumento() {
		return this.codiFmpgCodDocumento;
	}

	public void setCodiFmpgCodDocumento(String codiFmpgCodDocumento) {
		this.codiFmpgCodDocumento = codiFmpgCodDocumento;
	}

	public String getDescFmpgOggettoDocum() {
		return this.descFmpgOggettoDocum;
	}

	public void setDescFmpgOggettoDocum(String descFmpgOggettoDocum) {
		this.descFmpgOggettoDocum = descFmpgOggettoDocum;
	}

	public String getTextKcigTicoCodTipoContra() {
		return this.textKcigTicoCodTipoContra;
	}

	public void setTextKcigTicoCodTipoContra(String textKcigTicoCodTipoContra) {
		this.textKcigTicoCodTipoContra = textKcigTicoCodTipoContra;
	}

	public String getDescKcigTicoTipoContratto() {
		return this.descKcigTicoTipoContratto;
	}

	public void setDescKcigTicoTipoContratto(String descKcigTicoTipoContratto) {
		this.descKcigTicoTipoContratto = descKcigTicoTipoContratto;
	}

	public Date getDataFmpgVariante() {
		return this.dataFmpgVariante;
	}

	public void setDataFmpgVariante(Date dataFmpgVariante) {
		this.dataFmpgVariante = dataFmpgVariante;
	}

	public BigDecimal getImpoFmpgImpVariaAumento() {
		return this.impoFmpgImpVariaAumento;
	}

	public void setImpoFmpgImpVariaAumento(BigDecimal impoFmpgImpVariaAumento) {
		this.impoFmpgImpVariaAumento = impoFmpgImpVariaAumento;
	}

	public BigDecimal getImpoFmpgImpVariaDimin() {
		return this.impoFmpgImpVariaDimin;
	}

	public void setImpoFmpgImpVariaDimin(BigDecimal impoFmpgImpVariaDimin) {
		this.impoFmpgImpVariaDimin = impoFmpgImpVariaDimin;
	}

	public BigDecimal getNumFmpgNumeGiorniVar() {
		return this.numFmpgNumeGiorniVar;
	}

	public void setNumFmpgNumeGiorniVar(BigDecimal numFmpgNumeGiorniVar) {
		this.numFmpgNumeGiorniVar = numFmpgNumeGiorniVar;
	}

}
