package com.bruno.model.ho;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SwAnagprocaggiudic generated by hbm2java
 */
public class SwAnagprocaggiudic implements java.io.Serializable {

	private long sequSwAnagprocaggiudic;
	private String textKsogSoggCfiscale;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String codiKregKregId;
	private String descKregKregDescRegione;
	private String textCcupTipiCodTipInv;
	private String codiKcigCcigCodCig;
	private String descFagsDescrProcAgg;
	private short codiKpraPragCodTipoProc;
	private String descKpraPragDescrTipoProc;
	private BigDecimal impoFagsImpBaseAsta;
	private String descFagsNoteProcAgg;

	public SwAnagprocaggiudic() {
	}

	public SwAnagprocaggiudic(long sequSwAnagprocaggiudic,
			short codiKpraPragCodTipoProc, String descKpraPragDescrTipoProc) {
		this.sequSwAnagprocaggiudic = sequSwAnagprocaggiudic;
		this.codiKpraPragCodTipoProc = codiKpraPragCodTipoProc;
		this.descKpraPragDescrTipoProc = descKpraPragDescrTipoProc;
	}

	public SwAnagprocaggiudic(long sequSwAnagprocaggiudic,
			String textKsogSoggCfiscale, String textKsogFogiCodFormaGiur,
			String descKsogFogiDescFormaGiu, String codiCcupCcupAnagCcup,
			String textCcupSipiCodSetInv, String descCcupSipiDescSetCup,
			String textCcupSspiCodSsetInv, String descCcupSspiDescSsetCup,
			String textCcupCipiCodCatInv, String descCcupCipiDescCatCup,
			String codiKregKregId, String descKregKregDescRegione,
			String textCcupTipiCodTipInv, String codiKcigCcigCodCig,
			String descFagsDescrProcAgg, short codiKpraPragCodTipoProc,
			String descKpraPragDescrTipoProc, BigDecimal impoFagsImpBaseAsta,
			String descFagsNoteProcAgg) {
		this.sequSwAnagprocaggiudic = sequSwAnagprocaggiudic;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.codiKregKregId = codiKregKregId;
		this.descKregKregDescRegione = descKregKregDescRegione;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
		this.descFagsDescrProcAgg = descFagsDescrProcAgg;
		this.codiKpraPragCodTipoProc = codiKpraPragCodTipoProc;
		this.descKpraPragDescrTipoProc = descKpraPragDescrTipoProc;
		this.impoFagsImpBaseAsta = impoFagsImpBaseAsta;
		this.descFagsNoteProcAgg = descFagsNoteProcAgg;
	}

	public long getSequSwAnagprocaggiudic() {
		return this.sequSwAnagprocaggiudic;
	}

	public void setSequSwAnagprocaggiudic(long sequSwAnagprocaggiudic) {
		this.sequSwAnagprocaggiudic = sequSwAnagprocaggiudic;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getCodiKregKregId() {
		return this.codiKregKregId;
	}

	public void setCodiKregKregId(String codiKregKregId) {
		this.codiKregKregId = codiKregKregId;
	}

	public String getDescKregKregDescRegione() {
		return this.descKregKregDescRegione;
	}

	public void setDescKregKregDescRegione(String descKregKregDescRegione) {
		this.descKregKregDescRegione = descKregKregDescRegione;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getCodiKcigCcigCodCig() {
		return this.codiKcigCcigCodCig;
	}

	public void setCodiKcigCcigCodCig(String codiKcigCcigCodCig) {
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
	}

	public String getDescFagsDescrProcAgg() {
		return this.descFagsDescrProcAgg;
	}

	public void setDescFagsDescrProcAgg(String descFagsDescrProcAgg) {
		this.descFagsDescrProcAgg = descFagsDescrProcAgg;
	}

	public short getCodiKpraPragCodTipoProc() {
		return this.codiKpraPragCodTipoProc;
	}

	public void setCodiKpraPragCodTipoProc(short codiKpraPragCodTipoProc) {
		this.codiKpraPragCodTipoProc = codiKpraPragCodTipoProc;
	}

	public String getDescKpraPragDescrTipoProc() {
		return this.descKpraPragDescrTipoProc;
	}

	public void setDescKpraPragDescrTipoProc(String descKpraPragDescrTipoProc) {
		this.descKpraPragDescrTipoProc = descKpraPragDescrTipoProc;
	}

	public BigDecimal getImpoFagsImpBaseAsta() {
		return this.impoFagsImpBaseAsta;
	}

	public void setImpoFagsImpBaseAsta(BigDecimal impoFagsImpBaseAsta) {
		this.impoFagsImpBaseAsta = impoFagsImpBaseAsta;
	}

	public String getDescFagsNoteProcAgg() {
		return this.descFagsNoteProcAgg;
	}

	public void setDescFagsNoteProcAgg(String descFagsNoteProcAgg) {
		this.descFagsNoteProcAgg = descFagsNoteProcAgg;
	}

}
