package com.bruno.model.ho;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SwFinanziamenti generated by hbm2java
 */
public class SwFinanziamenti implements java.io.Serializable {

	private long sequSwFinanziamenti;
	private String textKsogSoggCfiscale;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String codiKregKregId;
	private String descKregKregDescRegione;
	private String textCodFonte;
	private String descDimensione;
	private String textCcupTipiCodTipInv;
	private String codiKurpUrpiCodLocProg;
	private String codiKffpFfpiCodFonteFina;
	private String descKffpFfpiDescrizFonte;
	private BigDecimal impoFmfpFonteFinanz;
	private Short annoPlauPlauAnno;
	private Byte numePlauPlauNumeTipo;
	private Integer numePlauPlauNume;
	private String descFmfpEstrProvv;
	private String textFmfpEstrDelibCipe;
	private Short annoFmfpDelibCipe;
	private String codiKprvKprvCodProvincia;
	private String textKprvKprvDescProvincia;
	private String codiKcomKcomId;
	private String textKcomKcomDescComune;
	private String descFmfpContrFinanz;
	private String textFmfpCfContrFinanz;
	private String flagFmfpEconDeriv;
	private String textFmfpNote;

	public SwFinanziamenti() {
	}

	public SwFinanziamenti(long sequSwFinanziamenti) {
		this.sequSwFinanziamenti = sequSwFinanziamenti;
	}

	public SwFinanziamenti(long sequSwFinanziamenti,
			String textKsogSoggCfiscale, String textKsogFogiCodFormaGiur,
			String descKsogFogiDescFormaGiu, String codiCcupCcupAnagCcup,
			String textCcupSipiCodSetInv, String descCcupSipiDescSetCup,
			String textCcupSspiCodSsetInv, String descCcupSspiDescSsetCup,
			String textCcupCipiCodCatInv, String descCcupCipiDescCatCup,
			String codiKregKregId, String descKregKregDescRegione,
			String textCodFonte, String descDimensione,
			String textCcupTipiCodTipInv, String codiKurpUrpiCodLocProg,
			String codiKffpFfpiCodFonteFina, String descKffpFfpiDescrizFonte,
			BigDecimal impoFmfpFonteFinanz, Short annoPlauPlauAnno,
			Byte numePlauPlauNumeTipo, Integer numePlauPlauNume,
			String descFmfpEstrProvv, String textFmfpEstrDelibCipe,
			Short annoFmfpDelibCipe, String codiKprvKprvCodProvincia,
			String textKprvKprvDescProvincia, String codiKcomKcomId,
			String textKcomKcomDescComune, String descFmfpContrFinanz,
			String textFmfpCfContrFinanz, String flagFmfpEconDeriv,
			String textFmfpNote) {
		this.sequSwFinanziamenti = sequSwFinanziamenti;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.codiKregKregId = codiKregKregId;
		this.descKregKregDescRegione = descKregKregDescRegione;
		this.textCodFonte = textCodFonte;
		this.descDimensione = descDimensione;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
		this.codiKffpFfpiCodFonteFina = codiKffpFfpiCodFonteFina;
		this.descKffpFfpiDescrizFonte = descKffpFfpiDescrizFonte;
		this.impoFmfpFonteFinanz = impoFmfpFonteFinanz;
		this.annoPlauPlauAnno = annoPlauPlauAnno;
		this.numePlauPlauNumeTipo = numePlauPlauNumeTipo;
		this.numePlauPlauNume = numePlauPlauNume;
		this.descFmfpEstrProvv = descFmfpEstrProvv;
		this.textFmfpEstrDelibCipe = textFmfpEstrDelibCipe;
		this.annoFmfpDelibCipe = annoFmfpDelibCipe;
		this.codiKprvKprvCodProvincia = codiKprvKprvCodProvincia;
		this.textKprvKprvDescProvincia = textKprvKprvDescProvincia;
		this.codiKcomKcomId = codiKcomKcomId;
		this.textKcomKcomDescComune = textKcomKcomDescComune;
		this.descFmfpContrFinanz = descFmfpContrFinanz;
		this.textFmfpCfContrFinanz = textFmfpCfContrFinanz;
		this.flagFmfpEconDeriv = flagFmfpEconDeriv;
		this.textFmfpNote = textFmfpNote;
	}

	public long getSequSwFinanziamenti() {
		return this.sequSwFinanziamenti;
	}

	public void setSequSwFinanziamenti(long sequSwFinanziamenti) {
		this.sequSwFinanziamenti = sequSwFinanziamenti;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getCodiKregKregId() {
		return this.codiKregKregId;
	}

	public void setCodiKregKregId(String codiKregKregId) {
		this.codiKregKregId = codiKregKregId;
	}

	public String getDescKregKregDescRegione() {
		return this.descKregKregDescRegione;
	}

	public void setDescKregKregDescRegione(String descKregKregDescRegione) {
		this.descKregKregDescRegione = descKregKregDescRegione;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getDescDimensione() {
		return this.descDimensione;
	}

	public void setDescDimensione(String descDimensione) {
		this.descDimensione = descDimensione;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getCodiKurpUrpiCodLocProg() {
		return this.codiKurpUrpiCodLocProg;
	}

	public void setCodiKurpUrpiCodLocProg(String codiKurpUrpiCodLocProg) {
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
	}

	public String getCodiKffpFfpiCodFonteFina() {
		return this.codiKffpFfpiCodFonteFina;
	}

	public void setCodiKffpFfpiCodFonteFina(String codiKffpFfpiCodFonteFina) {
		this.codiKffpFfpiCodFonteFina = codiKffpFfpiCodFonteFina;
	}

	public String getDescKffpFfpiDescrizFonte() {
		return this.descKffpFfpiDescrizFonte;
	}

	public void setDescKffpFfpiDescrizFonte(String descKffpFfpiDescrizFonte) {
		this.descKffpFfpiDescrizFonte = descKffpFfpiDescrizFonte;
	}

	public BigDecimal getImpoFmfpFonteFinanz() {
		return this.impoFmfpFonteFinanz;
	}

	public void setImpoFmfpFonteFinanz(BigDecimal impoFmfpFonteFinanz) {
		this.impoFmfpFonteFinanz = impoFmfpFonteFinanz;
	}

	public Short getAnnoPlauPlauAnno() {
		return this.annoPlauPlauAnno;
	}

	public void setAnnoPlauPlauAnno(Short annoPlauPlauAnno) {
		this.annoPlauPlauAnno = annoPlauPlauAnno;
	}

	public Byte getNumePlauPlauNumeTipo() {
		return this.numePlauPlauNumeTipo;
	}

	public void setNumePlauPlauNumeTipo(Byte numePlauPlauNumeTipo) {
		this.numePlauPlauNumeTipo = numePlauPlauNumeTipo;
	}

	public Integer getNumePlauPlauNume() {
		return this.numePlauPlauNume;
	}

	public void setNumePlauPlauNume(Integer numePlauPlauNume) {
		this.numePlauPlauNume = numePlauPlauNume;
	}

	public String getDescFmfpEstrProvv() {
		return this.descFmfpEstrProvv;
	}

	public void setDescFmfpEstrProvv(String descFmfpEstrProvv) {
		this.descFmfpEstrProvv = descFmfpEstrProvv;
	}

	public String getTextFmfpEstrDelibCipe() {
		return this.textFmfpEstrDelibCipe;
	}

	public void setTextFmfpEstrDelibCipe(String textFmfpEstrDelibCipe) {
		this.textFmfpEstrDelibCipe = textFmfpEstrDelibCipe;
	}

	public Short getAnnoFmfpDelibCipe() {
		return this.annoFmfpDelibCipe;
	}

	public void setAnnoFmfpDelibCipe(Short annoFmfpDelibCipe) {
		this.annoFmfpDelibCipe = annoFmfpDelibCipe;
	}

	public String getCodiKprvKprvCodProvincia() {
		return this.codiKprvKprvCodProvincia;
	}

	public void setCodiKprvKprvCodProvincia(String codiKprvKprvCodProvincia) {
		this.codiKprvKprvCodProvincia = codiKprvKprvCodProvincia;
	}

	public String getTextKprvKprvDescProvincia() {
		return this.textKprvKprvDescProvincia;
	}

	public void setTextKprvKprvDescProvincia(String textKprvKprvDescProvincia) {
		this.textKprvKprvDescProvincia = textKprvKprvDescProvincia;
	}

	public String getCodiKcomKcomId() {
		return this.codiKcomKcomId;
	}

	public void setCodiKcomKcomId(String codiKcomKcomId) {
		this.codiKcomKcomId = codiKcomKcomId;
	}

	public String getTextKcomKcomDescComune() {
		return this.textKcomKcomDescComune;
	}

	public void setTextKcomKcomDescComune(String textKcomKcomDescComune) {
		this.textKcomKcomDescComune = textKcomKcomDescComune;
	}

	public String getDescFmfpContrFinanz() {
		return this.descFmfpContrFinanz;
	}

	public void setDescFmfpContrFinanz(String descFmfpContrFinanz) {
		this.descFmfpContrFinanz = descFmfpContrFinanz;
	}

	public String getTextFmfpCfContrFinanz() {
		return this.textFmfpCfContrFinanz;
	}

	public void setTextFmfpCfContrFinanz(String textFmfpCfContrFinanz) {
		this.textFmfpCfContrFinanz = textFmfpCfContrFinanz;
	}

	public String getFlagFmfpEconDeriv() {
		return this.flagFmfpEconDeriv;
	}

	public void setFlagFmfpEconDeriv(String flagFmfpEconDeriv) {
		this.flagFmfpEconDeriv = flagFmfpEconDeriv;
	}

	public String getTextFmfpNote() {
		return this.textFmfpNote;
	}

	public void setTextFmfpNote(String textFmfpNote) {
		this.textFmfpNote = textFmfpNote;
	}

}
