package com.bruno.model.ho;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SwIterprocaggiudic generated by hbm2java
 */
public class SwIterprocaggiudic implements java.io.Serializable {

	private long sequSwIterprocaggiudic;
	private String textKsogSoggCfiscale;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String codiKregKregId;
	private String descKregKregDescRegione;
	private String textCcupTipiCodTipInv;
	private String codiKcigCcigCodCig;
	private Short textKsteStppCodStep;
	private String descKsteStppDescrizione;
	private Date dataFstaDataPrevConcl;
	private Date dataFstaDataEffetConcl;
	private String textFstaDenomSoggComp;
	private BigDecimal impoFstaImportoStepAgg;
	private String codiKmscMoscCodMotivo;
	private String descKmscMoscDescMot;
	private String descFstaNoteStep;

	public SwIterprocaggiudic() {
	}

	public SwIterprocaggiudic(long sequSwIterprocaggiudic) {
		this.sequSwIterprocaggiudic = sequSwIterprocaggiudic;
	}

	public SwIterprocaggiudic(long sequSwIterprocaggiudic,
			String textKsogSoggCfiscale, String textKsogFogiCodFormaGiur,
			String descKsogFogiDescFormaGiu, String codiCcupCcupAnagCcup,
			String textCcupSipiCodSetInv, String descCcupSipiDescSetCup,
			String textCcupSspiCodSsetInv, String descCcupSspiDescSsetCup,
			String textCcupCipiCodCatInv, String descCcupCipiDescCatCup,
			String codiKregKregId, String descKregKregDescRegione,
			String textCcupTipiCodTipInv, String codiKcigCcigCodCig,
			Short textKsteStppCodStep, String descKsteStppDescrizione,
			Date dataFstaDataPrevConcl, Date dataFstaDataEffetConcl,
			String textFstaDenomSoggComp, BigDecimal impoFstaImportoStepAgg,
			String codiKmscMoscCodMotivo, String descKmscMoscDescMot,
			String descFstaNoteStep) {
		this.sequSwIterprocaggiudic = sequSwIterprocaggiudic;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.codiKregKregId = codiKregKregId;
		this.descKregKregDescRegione = descKregKregDescRegione;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
		this.textKsteStppCodStep = textKsteStppCodStep;
		this.descKsteStppDescrizione = descKsteStppDescrizione;
		this.dataFstaDataPrevConcl = dataFstaDataPrevConcl;
		this.dataFstaDataEffetConcl = dataFstaDataEffetConcl;
		this.textFstaDenomSoggComp = textFstaDenomSoggComp;
		this.impoFstaImportoStepAgg = impoFstaImportoStepAgg;
		this.codiKmscMoscCodMotivo = codiKmscMoscCodMotivo;
		this.descKmscMoscDescMot = descKmscMoscDescMot;
		this.descFstaNoteStep = descFstaNoteStep;
	}

	public long getSequSwIterprocaggiudic() {
		return this.sequSwIterprocaggiudic;
	}

	public void setSequSwIterprocaggiudic(long sequSwIterprocaggiudic) {
		this.sequSwIterprocaggiudic = sequSwIterprocaggiudic;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getCodiKregKregId() {
		return this.codiKregKregId;
	}

	public void setCodiKregKregId(String codiKregKregId) {
		this.codiKregKregId = codiKregKregId;
	}

	public String getDescKregKregDescRegione() {
		return this.descKregKregDescRegione;
	}

	public void setDescKregKregDescRegione(String descKregKregDescRegione) {
		this.descKregKregDescRegione = descKregKregDescRegione;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getCodiKcigCcigCodCig() {
		return this.codiKcigCcigCodCig;
	}

	public void setCodiKcigCcigCodCig(String codiKcigCcigCodCig) {
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
	}

	public Short getTextKsteStppCodStep() {
		return this.textKsteStppCodStep;
	}

	public void setTextKsteStppCodStep(Short textKsteStppCodStep) {
		this.textKsteStppCodStep = textKsteStppCodStep;
	}

	public String getDescKsteStppDescrizione() {
		return this.descKsteStppDescrizione;
	}

	public void setDescKsteStppDescrizione(String descKsteStppDescrizione) {
		this.descKsteStppDescrizione = descKsteStppDescrizione;
	}

	public Date getDataFstaDataPrevConcl() {
		return this.dataFstaDataPrevConcl;
	}

	public void setDataFstaDataPrevConcl(Date dataFstaDataPrevConcl) {
		this.dataFstaDataPrevConcl = dataFstaDataPrevConcl;
	}

	public Date getDataFstaDataEffetConcl() {
		return this.dataFstaDataEffetConcl;
	}

	public void setDataFstaDataEffetConcl(Date dataFstaDataEffetConcl) {
		this.dataFstaDataEffetConcl = dataFstaDataEffetConcl;
	}

	public String getTextFstaDenomSoggComp() {
		return this.textFstaDenomSoggComp;
	}

	public void setTextFstaDenomSoggComp(String textFstaDenomSoggComp) {
		this.textFstaDenomSoggComp = textFstaDenomSoggComp;
	}

	public BigDecimal getImpoFstaImportoStepAgg() {
		return this.impoFstaImportoStepAgg;
	}

	public void setImpoFstaImportoStepAgg(BigDecimal impoFstaImportoStepAgg) {
		this.impoFstaImportoStepAgg = impoFstaImportoStepAgg;
	}

	public String getCodiKmscMoscCodMotivo() {
		return this.codiKmscMoscCodMotivo;
	}

	public void setCodiKmscMoscCodMotivo(String codiKmscMoscCodMotivo) {
		this.codiKmscMoscCodMotivo = codiKmscMoscCodMotivo;
	}

	public String getDescKmscMoscDescMot() {
		return this.descKmscMoscDescMot;
	}

	public void setDescKmscMoscDescMot(String descKmscMoscDescMot) {
		this.descKmscMoscDescMot = descKmscMoscDescMot;
	}

	public String getDescFstaNoteStep() {
		return this.descFstaNoteStep;
	}

	public void setDescFstaNoteStep(String descFstaNoteStep) {
		this.descFstaNoteStep = descFstaNoteStep;
	}

}
