package com.bruno.model.ho;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SwIterprocedurale generated by hbm2java
 */
public class SwIterprocedurale implements java.io.Serializable {

	private long sequSwIterprocedurale;
	private String textKsogSoggCfiscale;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String codiKregKregId;
	private String descKregKregDescRegione;
	private String textCodFonte;
	private String descDimensione;
	private String textCcupTipiCodTipInv;
	private String codiKurpUrpiCodLocProg;
	private String codiKfapFareCodFase;
	private String descKfapFareDescFase;
	private Date dataFmrpDataIniFasePrev;
	private Date dataFmrpDataIniFaseEffe;
	private Date dataFmrpDataFinFasePrev;
	private Date dataFmrpDataFinFaseEffe;
	private String textFmrpSoggettoCompet;
	private String codiKmscMoscCodMotivo;
	private String descKmscMoscDescMot;
	private String textFmrpNote;

	public SwIterprocedurale() {
	}

	public SwIterprocedurale(long sequSwIterprocedurale) {
		this.sequSwIterprocedurale = sequSwIterprocedurale;
	}

	public SwIterprocedurale(long sequSwIterprocedurale,
			String textKsogSoggCfiscale, String textKsogFogiCodFormaGiur,
			String descKsogFogiDescFormaGiu, String codiCcupCcupAnagCcup,
			String textCcupSipiCodSetInv, String descCcupSipiDescSetCup,
			String textCcupSspiCodSsetInv, String descCcupSspiDescSsetCup,
			String textCcupCipiCodCatInv, String descCcupCipiDescCatCup,
			String codiKregKregId, String descKregKregDescRegione,
			String textCodFonte, String descDimensione,
			String textCcupTipiCodTipInv, String codiKurpUrpiCodLocProg,
			String codiKfapFareCodFase, String descKfapFareDescFase,
			Date dataFmrpDataIniFasePrev, Date dataFmrpDataIniFaseEffe,
			Date dataFmrpDataFinFasePrev, Date dataFmrpDataFinFaseEffe,
			String textFmrpSoggettoCompet, String codiKmscMoscCodMotivo,
			String descKmscMoscDescMot, String textFmrpNote) {
		this.sequSwIterprocedurale = sequSwIterprocedurale;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.codiKregKregId = codiKregKregId;
		this.descKregKregDescRegione = descKregKregDescRegione;
		this.textCodFonte = textCodFonte;
		this.descDimensione = descDimensione;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
		this.codiKfapFareCodFase = codiKfapFareCodFase;
		this.descKfapFareDescFase = descKfapFareDescFase;
		this.dataFmrpDataIniFasePrev = dataFmrpDataIniFasePrev;
		this.dataFmrpDataIniFaseEffe = dataFmrpDataIniFaseEffe;
		this.dataFmrpDataFinFasePrev = dataFmrpDataFinFasePrev;
		this.dataFmrpDataFinFaseEffe = dataFmrpDataFinFaseEffe;
		this.textFmrpSoggettoCompet = textFmrpSoggettoCompet;
		this.codiKmscMoscCodMotivo = codiKmscMoscCodMotivo;
		this.descKmscMoscDescMot = descKmscMoscDescMot;
		this.textFmrpNote = textFmrpNote;
	}

	public long getSequSwIterprocedurale() {
		return this.sequSwIterprocedurale;
	}

	public void setSequSwIterprocedurale(long sequSwIterprocedurale) {
		this.sequSwIterprocedurale = sequSwIterprocedurale;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getCodiKregKregId() {
		return this.codiKregKregId;
	}

	public void setCodiKregKregId(String codiKregKregId) {
		this.codiKregKregId = codiKregKregId;
	}

	public String getDescKregKregDescRegione() {
		return this.descKregKregDescRegione;
	}

	public void setDescKregKregDescRegione(String descKregKregDescRegione) {
		this.descKregKregDescRegione = descKregKregDescRegione;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getDescDimensione() {
		return this.descDimensione;
	}

	public void setDescDimensione(String descDimensione) {
		this.descDimensione = descDimensione;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getCodiKurpUrpiCodLocProg() {
		return this.codiKurpUrpiCodLocProg;
	}

	public void setCodiKurpUrpiCodLocProg(String codiKurpUrpiCodLocProg) {
		this.codiKurpUrpiCodLocProg = codiKurpUrpiCodLocProg;
	}

	public String getCodiKfapFareCodFase() {
		return this.codiKfapFareCodFase;
	}

	public void setCodiKfapFareCodFase(String codiKfapFareCodFase) {
		this.codiKfapFareCodFase = codiKfapFareCodFase;
	}

	public String getDescKfapFareDescFase() {
		return this.descKfapFareDescFase;
	}

	public void setDescKfapFareDescFase(String descKfapFareDescFase) {
		this.descKfapFareDescFase = descKfapFareDescFase;
	}

	public Date getDataFmrpDataIniFasePrev() {
		return this.dataFmrpDataIniFasePrev;
	}

	public void setDataFmrpDataIniFasePrev(Date dataFmrpDataIniFasePrev) {
		this.dataFmrpDataIniFasePrev = dataFmrpDataIniFasePrev;
	}

	public Date getDataFmrpDataIniFaseEffe() {
		return this.dataFmrpDataIniFaseEffe;
	}

	public void setDataFmrpDataIniFaseEffe(Date dataFmrpDataIniFaseEffe) {
		this.dataFmrpDataIniFaseEffe = dataFmrpDataIniFaseEffe;
	}

	public Date getDataFmrpDataFinFasePrev() {
		return this.dataFmrpDataFinFasePrev;
	}

	public void setDataFmrpDataFinFasePrev(Date dataFmrpDataFinFasePrev) {
		this.dataFmrpDataFinFasePrev = dataFmrpDataFinFasePrev;
	}

	public Date getDataFmrpDataFinFaseEffe() {
		return this.dataFmrpDataFinFaseEffe;
	}

	public void setDataFmrpDataFinFaseEffe(Date dataFmrpDataFinFaseEffe) {
		this.dataFmrpDataFinFaseEffe = dataFmrpDataFinFaseEffe;
	}

	public String getTextFmrpSoggettoCompet() {
		return this.textFmrpSoggettoCompet;
	}

	public void setTextFmrpSoggettoCompet(String textFmrpSoggettoCompet) {
		this.textFmrpSoggettoCompet = textFmrpSoggettoCompet;
	}

	public String getCodiKmscMoscCodMotivo() {
		return this.codiKmscMoscCodMotivo;
	}

	public void setCodiKmscMoscCodMotivo(String codiKmscMoscCodMotivo) {
		this.codiKmscMoscCodMotivo = codiKmscMoscCodMotivo;
	}

	public String getDescKmscMoscDescMot() {
		return this.descKmscMoscDescMot;
	}

	public void setDescKmscMoscDescMot(String descKmscMoscDescMot) {
		this.descKmscMoscDescMot = descKmscMoscDescMot;
	}

	public String getTextFmrpNote() {
		return this.textFmrpNote;
	}

	public void setTextFmrpNote(String textFmrpNote) {
		this.textFmrpNote = textFmrpNote;
	}

}
