package com.bruno.model.ho;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SwPagamentisiopeordini generated by hbm2java
 */
public class SwPagamentisiopeordini implements java.io.Serializable {

	private long sequSwPagamentisiopeordini;
	private String textKsogSoggCfiscale;
	private String textKsogSoggDenominazione;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String codiKregKregId;
	private String descKregKregDescRegione;
	private String textCodFonte;
	private String textCcupTipiCodTipInv;
	private String descCcupTipiDescTipCup;
	private String textCgesCgesCod;
	private String descCgesCgesDesc;
	private Date dataContabile;
	private BigDecimal impoFodcPagatoNetto;

	public SwPagamentisiopeordini() {
	}

	public SwPagamentisiopeordini(long sequSwPagamentisiopeordini) {
		this.sequSwPagamentisiopeordini = sequSwPagamentisiopeordini;
	}

	public SwPagamentisiopeordini(long sequSwPagamentisiopeordini,
			String textKsogSoggCfiscale, String textKsogSoggDenominazione,
			String textKsogFogiCodFormaGiur, String descKsogFogiDescFormaGiu,
			String codiCcupCcupAnagCcup, String textCcupSipiCodSetInv,
			String descCcupSipiDescSetCup, String textCcupSspiCodSsetInv,
			String descCcupSspiDescSsetCup, String textCcupCipiCodCatInv,
			String descCcupCipiDescCatCup, String codiKregKregId,
			String descKregKregDescRegione, String textCodFonte,
			String textCcupTipiCodTipInv, String descCcupTipiDescTipCup,
			String textCgesCgesCod, String descCgesCgesDesc,
			Date dataContabile, BigDecimal impoFodcPagatoNetto) {
		this.sequSwPagamentisiopeordini = sequSwPagamentisiopeordini;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.codiKregKregId = codiKregKregId;
		this.descKregKregDescRegione = descKregKregDescRegione;
		this.textCodFonte = textCodFonte;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.descCcupTipiDescTipCup = descCcupTipiDescTipCup;
		this.textCgesCgesCod = textCgesCgesCod;
		this.descCgesCgesDesc = descCgesCgesDesc;
		this.dataContabile = dataContabile;
		this.impoFodcPagatoNetto = impoFodcPagatoNetto;
	}

	public long getSequSwPagamentisiopeordini() {
		return this.sequSwPagamentisiopeordini;
	}

	public void setSequSwPagamentisiopeordini(long sequSwPagamentisiopeordini) {
		this.sequSwPagamentisiopeordini = sequSwPagamentisiopeordini;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogSoggDenominazione() {
		return this.textKsogSoggDenominazione;
	}

	public void setTextKsogSoggDenominazione(String textKsogSoggDenominazione) {
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getCodiKregKregId() {
		return this.codiKregKregId;
	}

	public void setCodiKregKregId(String codiKregKregId) {
		this.codiKregKregId = codiKregKregId;
	}

	public String getDescKregKregDescRegione() {
		return this.descKregKregDescRegione;
	}

	public void setDescKregKregDescRegione(String descKregKregDescRegione) {
		this.descKregKregDescRegione = descKregKregDescRegione;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getDescCcupTipiDescTipCup() {
		return this.descCcupTipiDescTipCup;
	}

	public void setDescCcupTipiDescTipCup(String descCcupTipiDescTipCup) {
		this.descCcupTipiDescTipCup = descCcupTipiDescTipCup;
	}

	public String getTextCgesCgesCod() {
		return this.textCgesCgesCod;
	}

	public void setTextCgesCgesCod(String textCgesCgesCod) {
		this.textCgesCgesCod = textCgesCgesCod;
	}

	public String getDescCgesCgesDesc() {
		return this.descCgesCgesDesc;
	}

	public void setDescCgesCgesDesc(String descCgesCgesDesc) {
		this.descCgesCgesDesc = descCgesCgesDesc;
	}

	public Date getDataContabile() {
		return this.dataContabile;
	}

	public void setDataContabile(Date dataContabile) {
		this.dataContabile = dataContabile;
	}

	public BigDecimal getImpoFodcPagatoNetto() {
		return this.impoFodcPagatoNetto;
	}

	public void setImpoFodcPagatoNetto(BigDecimal impoFodcPagatoNetto) {
		this.impoFodcPagatoNetto = impoFodcPagatoNetto;
	}

}
