package com.bruno.model.ho;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SwSoggetticorrelatianac generated by hbm2java
 */
public class SwSoggetticorrelatianac implements java.io.Serializable {

	private long sequSwSoggetticorrelatianac;
	private String textKsogSogCfiscaleStApp;
	private String textKsogSogDenStApp;
	private Integer codiKsogSoggCodSoggetto;
	private String textKsogSoggCfiscale;
	private String textKsogSoggDenominazione;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiCcupCcupAnagCcup;
	private String codiKcigCcigCodCig;
	private String textCcupCipiCodCatInv;
	private String descCcupCipiDescCatCup;
	private String textCcupSspiCodSsetInv;
	private String descCcupSspiDescSsetCup;
	private String textCcupSipiCodSetInv;
	private String descCcupSipiDescSetCup;
	private String textKcigKregCodRegione;
	private String descKcigKregDescRegione;
	private String textCodFonte;
	private String textCcupTipiCodTipInv;
	private String codiKrugRuavCodRuolo;
	private String descKrugRuavDescRuolo;
	private String textKcigKprvCodProvincia;
	private String descKcigKprvDescProvincia;
	private String codiEsteEsteCodStato;
	private String descEsteEsteDescrStato;
	private String codiKsaeSae0CodSettore;
	private String descKsaeSae1DescSettore;
	private Date dataBtcgDataInizioAss;
	private Date dataBtcgDataFineAss;
	private String textBtcgCfRapprLeg;
	private String textBtcgDenomRapprLeg;
	private String textBtcgIndirizzo;
	private String textBtcgCap;
	private String descBtcgDescrSede;
	private String textBtcgCodiceAusa;

	public SwSoggetticorrelatianac() {
	}

	public SwSoggetticorrelatianac(long sequSwSoggetticorrelatianac) {
		this.sequSwSoggetticorrelatianac = sequSwSoggetticorrelatianac;
	}

	public SwSoggetticorrelatianac(long sequSwSoggetticorrelatianac,
			String textKsogSogCfiscaleStApp, String textKsogSogDenStApp,
			Integer codiKsogSoggCodSoggetto, String textKsogSoggCfiscale,
			String textKsogSoggDenominazione, String textKsogFogiCodFormaGiur,
			String descKsogFogiDescFormaGiu, String codiCcupCcupAnagCcup,
			String codiKcigCcigCodCig, String textCcupCipiCodCatInv,
			String descCcupCipiDescCatCup, String textCcupSspiCodSsetInv,
			String descCcupSspiDescSsetCup, String textCcupSipiCodSetInv,
			String descCcupSipiDescSetCup, String textKcigKregCodRegione,
			String descKcigKregDescRegione, String textCodFonte,
			String textCcupTipiCodTipInv, String codiKrugRuavCodRuolo,
			String descKrugRuavDescRuolo, String textKcigKprvCodProvincia,
			String descKcigKprvDescProvincia, String codiEsteEsteCodStato,
			String descEsteEsteDescrStato, String codiKsaeSae0CodSettore,
			String descKsaeSae1DescSettore, Date dataBtcgDataInizioAss,
			Date dataBtcgDataFineAss, String textBtcgCfRapprLeg,
			String textBtcgDenomRapprLeg, String textBtcgIndirizzo,
			String textBtcgCap, String descBtcgDescrSede,
			String textBtcgCodiceAusa) {
		this.sequSwSoggetticorrelatianac = sequSwSoggetticorrelatianac;
		this.textKsogSogCfiscaleStApp = textKsogSogCfiscaleStApp;
		this.textKsogSogDenStApp = textKsogSogDenStApp;
		this.codiKsogSoggCodSoggetto = codiKsogSoggCodSoggetto;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
		this.textKcigKregCodRegione = textKcigKregCodRegione;
		this.descKcigKregDescRegione = descKcigKregDescRegione;
		this.textCodFonte = textCodFonte;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.codiKrugRuavCodRuolo = codiKrugRuavCodRuolo;
		this.descKrugRuavDescRuolo = descKrugRuavDescRuolo;
		this.textKcigKprvCodProvincia = textKcigKprvCodProvincia;
		this.descKcigKprvDescProvincia = descKcigKprvDescProvincia;
		this.codiEsteEsteCodStato = codiEsteEsteCodStato;
		this.descEsteEsteDescrStato = descEsteEsteDescrStato;
		this.codiKsaeSae0CodSettore = codiKsaeSae0CodSettore;
		this.descKsaeSae1DescSettore = descKsaeSae1DescSettore;
		this.dataBtcgDataInizioAss = dataBtcgDataInizioAss;
		this.dataBtcgDataFineAss = dataBtcgDataFineAss;
		this.textBtcgCfRapprLeg = textBtcgCfRapprLeg;
		this.textBtcgDenomRapprLeg = textBtcgDenomRapprLeg;
		this.textBtcgIndirizzo = textBtcgIndirizzo;
		this.textBtcgCap = textBtcgCap;
		this.descBtcgDescrSede = descBtcgDescrSede;
		this.textBtcgCodiceAusa = textBtcgCodiceAusa;
	}

	public long getSequSwSoggetticorrelatianac() {
		return this.sequSwSoggetticorrelatianac;
	}

	public void setSequSwSoggetticorrelatianac(long sequSwSoggetticorrelatianac) {
		this.sequSwSoggetticorrelatianac = sequSwSoggetticorrelatianac;
	}

	public String getTextKsogSogCfiscaleStApp() {
		return this.textKsogSogCfiscaleStApp;
	}

	public void setTextKsogSogCfiscaleStApp(String textKsogSogCfiscaleStApp) {
		this.textKsogSogCfiscaleStApp = textKsogSogCfiscaleStApp;
	}

	public String getTextKsogSogDenStApp() {
		return this.textKsogSogDenStApp;
	}

	public void setTextKsogSogDenStApp(String textKsogSogDenStApp) {
		this.textKsogSogDenStApp = textKsogSogDenStApp;
	}

	public Integer getCodiKsogSoggCodSoggetto() {
		return this.codiKsogSoggCodSoggetto;
	}

	public void setCodiKsogSoggCodSoggetto(Integer codiKsogSoggCodSoggetto) {
		this.codiKsogSoggCodSoggetto = codiKsogSoggCodSoggetto;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogSoggDenominazione() {
		return this.textKsogSoggDenominazione;
	}

	public void setTextKsogSoggDenominazione(String textKsogSoggDenominazione) {
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getCodiKcigCcigCodCig() {
		return this.codiKcigCcigCodCig;
	}

	public void setCodiKcigCcigCodCig(String codiKcigCcigCodCig) {
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
	}

	public String getTextCcupCipiCodCatInv() {
		return this.textCcupCipiCodCatInv;
	}

	public void setTextCcupCipiCodCatInv(String textCcupCipiCodCatInv) {
		this.textCcupCipiCodCatInv = textCcupCipiCodCatInv;
	}

	public String getDescCcupCipiDescCatCup() {
		return this.descCcupCipiDescCatCup;
	}

	public void setDescCcupCipiDescCatCup(String descCcupCipiDescCatCup) {
		this.descCcupCipiDescCatCup = descCcupCipiDescCatCup;
	}

	public String getTextCcupSspiCodSsetInv() {
		return this.textCcupSspiCodSsetInv;
	}

	public void setTextCcupSspiCodSsetInv(String textCcupSspiCodSsetInv) {
		this.textCcupSspiCodSsetInv = textCcupSspiCodSsetInv;
	}

	public String getDescCcupSspiDescSsetCup() {
		return this.descCcupSspiDescSsetCup;
	}

	public void setDescCcupSspiDescSsetCup(String descCcupSspiDescSsetCup) {
		this.descCcupSspiDescSsetCup = descCcupSspiDescSsetCup;
	}

	public String getTextCcupSipiCodSetInv() {
		return this.textCcupSipiCodSetInv;
	}

	public void setTextCcupSipiCodSetInv(String textCcupSipiCodSetInv) {
		this.textCcupSipiCodSetInv = textCcupSipiCodSetInv;
	}

	public String getDescCcupSipiDescSetCup() {
		return this.descCcupSipiDescSetCup;
	}

	public void setDescCcupSipiDescSetCup(String descCcupSipiDescSetCup) {
		this.descCcupSipiDescSetCup = descCcupSipiDescSetCup;
	}

	public String getTextKcigKregCodRegione() {
		return this.textKcigKregCodRegione;
	}

	public void setTextKcigKregCodRegione(String textKcigKregCodRegione) {
		this.textKcigKregCodRegione = textKcigKregCodRegione;
	}

	public String getDescKcigKregDescRegione() {
		return this.descKcigKregDescRegione;
	}

	public void setDescKcigKregDescRegione(String descKcigKregDescRegione) {
		this.descKcigKregDescRegione = descKcigKregDescRegione;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getCodiKrugRuavCodRuolo() {
		return this.codiKrugRuavCodRuolo;
	}

	public void setCodiKrugRuavCodRuolo(String codiKrugRuavCodRuolo) {
		this.codiKrugRuavCodRuolo = codiKrugRuavCodRuolo;
	}

	public String getDescKrugRuavDescRuolo() {
		return this.descKrugRuavDescRuolo;
	}

	public void setDescKrugRuavDescRuolo(String descKrugRuavDescRuolo) {
		this.descKrugRuavDescRuolo = descKrugRuavDescRuolo;
	}

	public String getTextKcigKprvCodProvincia() {
		return this.textKcigKprvCodProvincia;
	}

	public void setTextKcigKprvCodProvincia(String textKcigKprvCodProvincia) {
		this.textKcigKprvCodProvincia = textKcigKprvCodProvincia;
	}

	public String getDescKcigKprvDescProvincia() {
		return this.descKcigKprvDescProvincia;
	}

	public void setDescKcigKprvDescProvincia(String descKcigKprvDescProvincia) {
		this.descKcigKprvDescProvincia = descKcigKprvDescProvincia;
	}

	public String getCodiEsteEsteCodStato() {
		return this.codiEsteEsteCodStato;
	}

	public void setCodiEsteEsteCodStato(String codiEsteEsteCodStato) {
		this.codiEsteEsteCodStato = codiEsteEsteCodStato;
	}

	public String getDescEsteEsteDescrStato() {
		return this.descEsteEsteDescrStato;
	}

	public void setDescEsteEsteDescrStato(String descEsteEsteDescrStato) {
		this.descEsteEsteDescrStato = descEsteEsteDescrStato;
	}

	public String getCodiKsaeSae0CodSettore() {
		return this.codiKsaeSae0CodSettore;
	}

	public void setCodiKsaeSae0CodSettore(String codiKsaeSae0CodSettore) {
		this.codiKsaeSae0CodSettore = codiKsaeSae0CodSettore;
	}

	public String getDescKsaeSae1DescSettore() {
		return this.descKsaeSae1DescSettore;
	}

	public void setDescKsaeSae1DescSettore(String descKsaeSae1DescSettore) {
		this.descKsaeSae1DescSettore = descKsaeSae1DescSettore;
	}

	public Date getDataBtcgDataInizioAss() {
		return this.dataBtcgDataInizioAss;
	}

	public void setDataBtcgDataInizioAss(Date dataBtcgDataInizioAss) {
		this.dataBtcgDataInizioAss = dataBtcgDataInizioAss;
	}

	public Date getDataBtcgDataFineAss() {
		return this.dataBtcgDataFineAss;
	}

	public void setDataBtcgDataFineAss(Date dataBtcgDataFineAss) {
		this.dataBtcgDataFineAss = dataBtcgDataFineAss;
	}

	public String getTextBtcgCfRapprLeg() {
		return this.textBtcgCfRapprLeg;
	}

	public void setTextBtcgCfRapprLeg(String textBtcgCfRapprLeg) {
		this.textBtcgCfRapprLeg = textBtcgCfRapprLeg;
	}

	public String getTextBtcgDenomRapprLeg() {
		return this.textBtcgDenomRapprLeg;
	}

	public void setTextBtcgDenomRapprLeg(String textBtcgDenomRapprLeg) {
		this.textBtcgDenomRapprLeg = textBtcgDenomRapprLeg;
	}

	public String getTextBtcgIndirizzo() {
		return this.textBtcgIndirizzo;
	}

	public void setTextBtcgIndirizzo(String textBtcgIndirizzo) {
		this.textBtcgIndirizzo = textBtcgIndirizzo;
	}

	public String getTextBtcgCap() {
		return this.textBtcgCap;
	}

	public void setTextBtcgCap(String textBtcgCap) {
		this.textBtcgCap = textBtcgCap;
	}

	public String getDescBtcgDescrSede() {
		return this.descBtcgDescrSede;
	}

	public void setDescBtcgDescrSede(String descBtcgDescrSede) {
		this.descBtcgDescrSede = descBtcgDescrSede;
	}

	public String getTextBtcgCodiceAusa() {
		return this.textBtcgCodiceAusa;
	}

	public void setTextBtcgCodiceAusa(String textBtcgCodiceAusa) {
		this.textBtcgCodiceAusa = textBtcgCodiceAusa;
	}

}
