package com.bruno.model.ho;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

/**
 * SwSoggettiinvestimentipubb generated by hbm2java
 */
public class SwSoggettiinvestimentipubb implements java.io.Serializable {

	private long sequSwSoggettiinvestpubb;
	private String textKsogSoggCfiscale;
	private String textKsogSoggDenominazione;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;

	public SwSoggettiinvestimentipubb() {
	}

	public SwSoggettiinvestimentipubb(long sequSwSoggettiinvestpubb) {
		this.sequSwSoggettiinvestpubb = sequSwSoggettiinvestpubb;
	}

	public SwSoggettiinvestimentipubb(long sequSwSoggettiinvestpubb,
			String textKsogSoggCfiscale, String textKsogSoggDenominazione,
			String textKsogFogiCodFormaGiur, String descKsogFogiDescFormaGiu) {
		this.sequSwSoggettiinvestpubb = sequSwSoggettiinvestpubb;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public long getSequSwSoggettiinvestpubb() {
		return this.sequSwSoggettiinvestpubb;
	}

	public void setSequSwSoggettiinvestpubb(long sequSwSoggettiinvestpubb) {
		this.sequSwSoggettiinvestpubb = sequSwSoggettiinvestpubb;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogSoggDenominazione() {
		return this.textKsogSoggDenominazione;
	}

	public void setTextKsogSoggDenominazione(String textKsogSoggDenominazione) {
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

}
