package com.bruno.model.ho;

// Generated Sep 6, 2016 2:40:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SwStepfasicig generated by hbm2java
 */
public class SwStepfasicig implements java.io.Serializable {

	private long sequSwStepfasicig;
	private String textKsogSogCfiscaleStApp;
	private String textKsogSogDenStApp;
	private String textKsogSoggCfiscale;
	private String textKsogSoggDenominazione;
	private String textKsogFogiCodFormaGiur;
	private String descKsogFogiDescFormaGiu;
	private String codiKcigCcigCodCig;
	private String codiCcupCcupAnagCcup;
	private String textKurpCipiCodCatInv;
	private String descKurpCipiDescCatCup;
	private String textKurpSspiCodSsetInv;
	private String descKurpSspiDescSsetCup;
	private String textKurpSipiCodSetInv;
	private String descKurpSipiDescSetCup;
	private String textKcigKregCodRegione;
	private String descKcigKregDescRegione;
	private String textCodFonte;
	private String textCcupTipiCodTipInv;
	private String textKfasStepCodStep;
	private String descKfasStepDescStep;
	private BigDecimal impoFmpgImpDocumStep;

	public SwStepfasicig() {
	}

	public SwStepfasicig(long sequSwStepfasicig) {
		this.sequSwStepfasicig = sequSwStepfasicig;
	}

	public SwStepfasicig(long sequSwStepfasicig,
			String textKsogSogCfiscaleStApp, String textKsogSogDenStApp,
			String textKsogSoggCfiscale, String textKsogSoggDenominazione,
			String textKsogFogiCodFormaGiur, String descKsogFogiDescFormaGiu,
			String codiKcigCcigCodCig, String codiCcupCcupAnagCcup,
			String textKurpCipiCodCatInv, String descKurpCipiDescCatCup,
			String textKurpSspiCodSsetInv, String descKurpSspiDescSsetCup,
			String textKurpSipiCodSetInv, String descKurpSipiDescSetCup,
			String textKcigKregCodRegione, String descKcigKregDescRegione,
			String textCodFonte, String textCcupTipiCodTipInv,
			String textKfasStepCodStep, String descKfasStepDescStep,
			BigDecimal impoFmpgImpDocumStep) {
		this.sequSwStepfasicig = sequSwStepfasicig;
		this.textKsogSogCfiscaleStApp = textKsogSogCfiscaleStApp;
		this.textKsogSogDenStApp = textKsogSogDenStApp;
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
		this.textKurpCipiCodCatInv = textKurpCipiCodCatInv;
		this.descKurpCipiDescCatCup = descKurpCipiDescCatCup;
		this.textKurpSspiCodSsetInv = textKurpSspiCodSsetInv;
		this.descKurpSspiDescSsetCup = descKurpSspiDescSsetCup;
		this.textKurpSipiCodSetInv = textKurpSipiCodSetInv;
		this.descKurpSipiDescSetCup = descKurpSipiDescSetCup;
		this.textKcigKregCodRegione = textKcigKregCodRegione;
		this.descKcigKregDescRegione = descKcigKregDescRegione;
		this.textCodFonte = textCodFonte;
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
		this.textKfasStepCodStep = textKfasStepCodStep;
		this.descKfasStepDescStep = descKfasStepDescStep;
		this.impoFmpgImpDocumStep = impoFmpgImpDocumStep;
	}

	public long getSequSwStepfasicig() {
		return this.sequSwStepfasicig;
	}

	public void setSequSwStepfasicig(long sequSwStepfasicig) {
		this.sequSwStepfasicig = sequSwStepfasicig;
	}

	public String getTextKsogSogCfiscaleStApp() {
		return this.textKsogSogCfiscaleStApp;
	}

	public void setTextKsogSogCfiscaleStApp(String textKsogSogCfiscaleStApp) {
		this.textKsogSogCfiscaleStApp = textKsogSogCfiscaleStApp;
	}

	public String getTextKsogSogDenStApp() {
		return this.textKsogSogDenStApp;
	}

	public void setTextKsogSogDenStApp(String textKsogSogDenStApp) {
		this.textKsogSogDenStApp = textKsogSogDenStApp;
	}

	public String getTextKsogSoggCfiscale() {
		return this.textKsogSoggCfiscale;
	}

	public void setTextKsogSoggCfiscale(String textKsogSoggCfiscale) {
		this.textKsogSoggCfiscale = textKsogSoggCfiscale;
	}

	public String getTextKsogSoggDenominazione() {
		return this.textKsogSoggDenominazione;
	}

	public void setTextKsogSoggDenominazione(String textKsogSoggDenominazione) {
		this.textKsogSoggDenominazione = textKsogSoggDenominazione;
	}

	public String getTextKsogFogiCodFormaGiur() {
		return this.textKsogFogiCodFormaGiur;
	}

	public void setTextKsogFogiCodFormaGiur(String textKsogFogiCodFormaGiur) {
		this.textKsogFogiCodFormaGiur = textKsogFogiCodFormaGiur;
	}

	public String getDescKsogFogiDescFormaGiu() {
		return this.descKsogFogiDescFormaGiu;
	}

	public void setDescKsogFogiDescFormaGiu(String descKsogFogiDescFormaGiu) {
		this.descKsogFogiDescFormaGiu = descKsogFogiDescFormaGiu;
	}

	public String getCodiKcigCcigCodCig() {
		return this.codiKcigCcigCodCig;
	}

	public void setCodiKcigCcigCodCig(String codiKcigCcigCodCig) {
		this.codiKcigCcigCodCig = codiKcigCcigCodCig;
	}

	public String getCodiCcupCcupAnagCcup() {
		return this.codiCcupCcupAnagCcup;
	}

	public void setCodiCcupCcupAnagCcup(String codiCcupCcupAnagCcup) {
		this.codiCcupCcupAnagCcup = codiCcupCcupAnagCcup;
	}

	public String getTextKurpCipiCodCatInv() {
		return this.textKurpCipiCodCatInv;
	}

	public void setTextKurpCipiCodCatInv(String textKurpCipiCodCatInv) {
		this.textKurpCipiCodCatInv = textKurpCipiCodCatInv;
	}

	public String getDescKurpCipiDescCatCup() {
		return this.descKurpCipiDescCatCup;
	}

	public void setDescKurpCipiDescCatCup(String descKurpCipiDescCatCup) {
		this.descKurpCipiDescCatCup = descKurpCipiDescCatCup;
	}

	public String getTextKurpSspiCodSsetInv() {
		return this.textKurpSspiCodSsetInv;
	}

	public void setTextKurpSspiCodSsetInv(String textKurpSspiCodSsetInv) {
		this.textKurpSspiCodSsetInv = textKurpSspiCodSsetInv;
	}

	public String getDescKurpSspiDescSsetCup() {
		return this.descKurpSspiDescSsetCup;
	}

	public void setDescKurpSspiDescSsetCup(String descKurpSspiDescSsetCup) {
		this.descKurpSspiDescSsetCup = descKurpSspiDescSsetCup;
	}

	public String getTextKurpSipiCodSetInv() {
		return this.textKurpSipiCodSetInv;
	}

	public void setTextKurpSipiCodSetInv(String textKurpSipiCodSetInv) {
		this.textKurpSipiCodSetInv = textKurpSipiCodSetInv;
	}

	public String getDescKurpSipiDescSetCup() {
		return this.descKurpSipiDescSetCup;
	}

	public void setDescKurpSipiDescSetCup(String descKurpSipiDescSetCup) {
		this.descKurpSipiDescSetCup = descKurpSipiDescSetCup;
	}

	public String getTextKcigKregCodRegione() {
		return this.textKcigKregCodRegione;
	}

	public void setTextKcigKregCodRegione(String textKcigKregCodRegione) {
		this.textKcigKregCodRegione = textKcigKregCodRegione;
	}

	public String getDescKcigKregDescRegione() {
		return this.descKcigKregDescRegione;
	}

	public void setDescKcigKregDescRegione(String descKcigKregDescRegione) {
		this.descKcigKregDescRegione = descKcigKregDescRegione;
	}

	public String getTextCodFonte() {
		return this.textCodFonte;
	}

	public void setTextCodFonte(String textCodFonte) {
		this.textCodFonte = textCodFonte;
	}

	public String getTextCcupTipiCodTipInv() {
		return this.textCcupTipiCodTipInv;
	}

	public void setTextCcupTipiCodTipInv(String textCcupTipiCodTipInv) {
		this.textCcupTipiCodTipInv = textCcupTipiCodTipInv;
	}

	public String getTextKfasStepCodStep() {
		return this.textKfasStepCodStep;
	}

	public void setTextKfasStepCodStep(String textKfasStepCodStep) {
		this.textKfasStepCodStep = textKfasStepCodStep;
	}

	public String getDescKfasStepDescStep() {
		return this.descKfasStepDescStep;
	}

	public void setDescKfasStepDescStep(String descKfasStepDescStep) {
		this.descKfasStepDescStep = descKfasStepDescStep;
	}

	public BigDecimal getImpoFmpgImpDocumStep() {
		return this.impoFmpgImpDocumStep;
	}

	public void setImpoFmpgImpDocumStep(BigDecimal impoFmpgImpDocumStep) {
		this.impoFmpgImpDocumStep = impoFmpgImpDocumStep;
	}

}
